import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { resolveAuthenticatedRepositoryContext } from "@/lib/auth/repository-context";
import { createServerSupabaseClient } from "@/lib/supabase/server";

type CompensationRow = { id: string; record_type?: string; currency?: string; amount_min?: number; amount_max?: number; amount_exact?: number; decision_date?: string; occurred_at?: string; created_at: string; payload: Record<string, unknown> };

export default async function LiveCompensationPage() {
  const resolved = await resolveAuthenticatedRepositoryContext();
  if (!resolved) redirect("/login?next=/compensation");
  const response = await createServerSupabaseClient(resolved.accessToken).request<CompensationRow[]>(`compensation_records?select=id,record_type,currency,amount_min,amount_max,amount_exact,decision_date,occurred_at,created_at,payload&workspace_id=eq.${resolved.context.workspace!.workspaceId}&archived_at=is.null&order=occurred_at.desc,created_at.desc`);
  if (response.error) throw new Error("Private compensation history could not be loaded safely.");
  const records = response.data ?? [];
  return <main className="mx-auto max-w-5xl px-5 py-10 sm:px-6 lg:px-10"><PageHeader eyebrow="Private career memory" title="Compensation history" description="Salary, bonus, commission, equity, and negotiation evidence remain in their original currency. ORENDALIS does not convert or infer missing values." actions={<Link href="/applications" className="inline-flex rounded-xl border border-[#d9dcde] bg-white px-5 py-3 text-sm font-semibold">View applications</Link>}/>{records.length ? <div className="mt-8 space-y-4">{records.map((record) => <article key={record.id} className="rounded-2xl border border-[#e3e5e6] bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#936b3f]">{record.record_type || "Compensation evidence"}</p><h2 className="mt-2 text-2xl font-semibold text-[#17191c]">{amount(record)}</h2></div><p className="text-sm text-[#747b82]">{record.decision_date || date(record.occurred_at ?? record.created_at)}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Bonus" value={text(record.payload.bonus)}/><Fact label="Commission" value={text(record.payload.commission)}/><Fact label="Equity" value={text(record.payload.equity)}/><Fact label="Normalization" value={normalization(record.payload)}/></div><p className="mt-4 text-xs text-[#8a8f93]">Append-only record. New negotiation or offer events are added without rewriting earlier evidence.</p></article>)}</div> : <section className="mt-8 rounded-2xl border border-dashed border-[#cfc7bc] bg-[#faf8f4] p-8 text-center"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#936b3f]">No compensation records</p><h2 className="mt-3 text-2xl font-semibold">Compensation remains unknown until you confirm it</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#626970]">Published ranges and negotiation events will appear here only when they are part of a real opportunity or application.</p></section>}</main>;
}

function amount(record: CompensationRow) { const currency = record.currency ?? "Currency unknown"; if (record.amount_exact !== undefined) return `${currency} ${Number(record.amount_exact).toLocaleString("en-GB")}`; if (record.amount_min !== undefined || record.amount_max !== undefined) return `${currency} ${record.amount_min !== undefined ? Number(record.amount_min).toLocaleString("en-GB") : "?"}–${record.amount_max !== undefined ? Number(record.amount_max).toLocaleString("en-GB") : "?"}`; return "Amount not confirmed"; }
function normalization(payload: Record<string, unknown>) { if (payload.conversionApplied === true) return typeof payload.normalizationMethod === "string" ? payload.normalizationMethod : "Conversion recorded"; return "Original currency preserved"; }
function text(value: unknown) { return typeof value === "string" && value.trim() ? value : typeof value === "number" ? String(value) : "Not confirmed"; }
function date(value?: string) { return value ? new Date(value).toLocaleDateString("en-GB") : "Date not confirmed"; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#f7f7f5] p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#8a8f93]">{label}</p><p className="mt-2 text-sm text-[#30343a]">{value}</p></div>; }
