import { StatusBadge } from "@/components/status-badge";
import { addAtlasDecisionNoteAction, addAtlasWorkspaceEvidenceAction, addAtlasWorkspaceQuestionAction, addAtlasWorkspaceTaskAction, changeAtlasDecisionStageAction, changeAtlasWorkspaceTaskAction, completeAtlasWorkspaceQuestionAction, requestAtlasReassessmentAction, reviewAtlasWorkspaceEvidenceAction } from "@/app/opportunities/actions";
import { nextDecisionStages, type AtlasDecisionWorkspace } from "@/lib/discovery/atlas-decision-workspace";
import type { ReactNode } from "react";

const field = "w-full rounded-xl border border-[#d9dcde] bg-white px-3 py-2 text-sm text-[#17191c] placeholder:text-[#8a9095]";
const button = "rounded-xl bg-[#17191c] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#303337] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#55778a]";
const secondary = "rounded-xl border border-[#d9dcde] bg-white px-3 py-2 text-sm font-semibold text-[#303337] hover:bg-[#f7f8f8]";

export function AtlasDecisionWorkspacePanel({ opportunityId, workspace, persisted }: { opportunityId: string; workspace: AtlasDecisionWorkspace; persisted: boolean }) {
  const review = workspace.reviews.at(-1)!;
  const confidence = review.objects.find((item) => item.kind === "Confidence Statement")?.confidence;
  const recommendation = review.objects.find((item) => item.kind === "Recommendation");
  const unknowns = review.objects.find((item) => item.kind === "Unknown Statement")?.unknowns ?? [];
  const conflicts = review.objects.find((item) => item.kind === "Conflict Statement")?.conflicts ?? [];
  const evidence = review.objects.find((item) => item.kind === "Evidence Summary");
  const reviewedEvidence = workspace.evidence.filter((item) => item.reviewStatus === "Reviewed");
  const newReviewedEvidence = reviewedEvidence.filter((item) => !review.sourceEvidenceIds.includes(item.id));
  const nextStages = nextDecisionStages(workspace.currentStage);
  return <section aria-labelledby="atlas-workspace-title" className="mx-auto max-w-6xl px-5 pb-12 sm:px-6 lg:px-10">
    <div className="rounded-3xl border border-[#dfe7ea] bg-[#f5f8f9] p-5 sm:p-7">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6f8796]">Atlas decision workspace</p><h2 id="atlas-workspace-title" className="mt-2 text-2xl font-semibold">Continue this decision with evidence</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#626970]">Your review, investigation, and decision history stay together so you can resume without losing context.</p></div><div className="flex flex-wrap gap-2"><StatusBadge tone={review.state === "Recommendation Available" ? "success" : "warning"}>{review.state}</StatusBadge><StatusBadge tone="neutral">{workspace.currentStage}</StatusBadge><StatusBadge tone={persisted ? "success" : "info"}>{persisted ? "Saved" : "Ready to save"}</StatusBadge></div></div>

      <div className="mt-6 grid gap-4 md:grid-cols-3"><Summary label="Atlas view" value={recommendation?.statement ?? "Recommendation withheld until the evidence gates pass."}/><Summary label="Confidence" value={confidence ? `${confidence.level} · ${confidence.score ?? "not scored"}` : "Unknown"}/><Summary label="Decision history" value={`${workspace.reviews.length} review${workspace.reviews.length === 1 ? "" : "s"} · ${workspace.decisions.length} recorded decision${workspace.decisions.length === 1 ? "" : "s"}`}/></div>

      <details open className="mt-5 rounded-2xl border border-[#e3e5e6] bg-white p-5"><summary className="cursor-pointer font-semibold">Opportunity review</summary><div className="mt-4 grid gap-5 md:grid-cols-2"><List title="Supporting evidence" items={evidence?.facts ?? []} empty="No supported fact is available yet."/><List title="Known unknowns" items={unknowns} empty="No material unknown is recorded."/><List title="Conflicting evidence" items={conflicts} empty="No unresolved conflict is recorded."/><List title="Suggested next investigations" items={review.objects.flatMap((item) => item.suggestedActions)} empty="No investigation is currently suggested."/></div></details>

      <div className="mt-5 grid gap-5 lg:grid-cols-2">
        <WorkspaceCard title="Evidence collection" subtitle="Add only evidence you can identify. Review it before Atlas can use it.">
          <form action={addAtlasWorkspaceEvidenceAction} className="grid gap-2"><Hidden id={opportunityId}/><input name="statement" required maxLength={1000} className={field} placeholder="What did you learn?"/><input name="reference" required maxLength={1000} className={field} placeholder="Source or reference"/><button className={button}>Add evidence</button></form>
          <div className="mt-4 space-y-3">{workspace.evidence.map((item) => <div key={item.id} className="rounded-xl bg-[#f7f8f8] p-3 text-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.statement}</p><p className="mt-1 break-all text-xs text-[#6f757b]">{item.reference}</p></div><StatusBadge tone={item.reviewStatus === "Reviewed" ? "success" : "warning"}>{item.reviewStatus}</StatusBadge></div>{item.reviewStatus === "Pending Review" && <form action={reviewAtlasWorkspaceEvidenceAction} className="mt-3"><Hidden id={opportunityId}/><input type="hidden" name="evidenceId" value={item.id}/><button className={secondary}>Mark reviewed</button></form>}</div>)}</div>
        </WorkspaceCard>

        <WorkspaceCard title="Decision stage" subtitle="You control progression. Atlas never advances a stage for you.">
          <p className="text-sm"><span className="text-[#6f757b]">Current:</span> <strong>{workspace.currentStage}</strong></p>{nextStages.length ? <form action={changeAtlasDecisionStageAction} className="mt-3 grid gap-2"><Hidden id={opportunityId}/><select name="toStage" className={field} defaultValue={nextStages[0]}>{nextStages.map((stage) => <option key={stage}>{stage}</option>)}</select><input name="reason" required maxLength={1000} className={field} placeholder="Why are you moving this forward?"/><button className={button}>Update stage</button></form> : <p className="mt-3 text-sm text-[#6f757b]">This decision journey is archived.</p>}
        </WorkspaceCard>

        <WorkspaceCard title="Executive tasks" subtitle="Tasks remain suggestions until you choose to act.">
          <form action={addAtlasWorkspaceTaskAction} className="flex gap-2"><Hidden id={opportunityId}/><input name="title" required maxLength={500} className={field} placeholder="Add an investigation task"/><button className={button}>Add</button></form><div className="mt-4 space-y-2">{workspace.tasks.map((task) => <div key={task.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-[#f7f8f8] p-3 text-sm"><div><p className="font-medium">{task.title}</p><p className="text-xs text-[#6f757b]">{task.source} · {task.status}</p></div>{(task.status === "Open" || task.status === "Suggested") && <form action={changeAtlasWorkspaceTaskAction}><Hidden id={opportunityId}/><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="status" value={task.status === "Suggested" ? "Open" : "Completed"}/><button className={secondary}>{task.status === "Suggested" ? "Accept task" : "Complete"}</button></form>}</div>)}</div>
        </WorkspaceCard>

        <WorkspaceCard title="Decision notes" subtitle="Notes preserve your judgment but do not become evidence automatically."><form action={addAtlasDecisionNoteAction} className="grid gap-2"><Hidden id={opportunityId}/><textarea name="text" required maxLength={1000} className={field} placeholder="Record your current view"/><button className={button}>Add note</button></form><div className="mt-4 space-y-2">{workspace.notes.map((note) => <blockquote key={note.id} className="rounded-xl bg-[#f7f8f8] p-3 text-sm">{note.text}<footer className="mt-1 text-xs text-[#6f757b]">{new Date(note.createdAt).toLocaleString("en")}</footer></blockquote>)}</div></WorkspaceCard>

        <WorkspaceCard title="Open questions" subtitle="A question can be completed only with reviewed evidence."><form action={addAtlasWorkspaceQuestionAction} className="flex gap-2"><Hidden id={opportunityId}/><input name="question" required maxLength={1000} className={field} placeholder="What must be answered?"/><button className={button}>Add</button></form><div className="mt-4 space-y-3">{workspace.questions.map((question) => <div key={question.id} className="rounded-xl bg-[#f7f8f8] p-3 text-sm"><p className="font-medium">{question.question}</p>{question.status === "Completed" ? <p className="mt-2 text-[#53616a]">{question.answer}</p> : reviewedEvidence.length ? <form action={completeAtlasWorkspaceQuestionAction} className="mt-3 grid gap-2"><Hidden id={opportunityId}/><input type="hidden" name="questionId" value={question.id}/><select name="evidenceId" className={field}>{reviewedEvidence.map((item) => <option key={item.id} value={item.id}>{item.statement}</option>)}</select><input name="answer" required maxLength={1000} className={field} placeholder="Evidence-backed answer"/><button className={secondary}>Complete question</button></form> : <p className="mt-2 text-xs text-[#6f757b]">Review evidence before completing this question.</p>}</div>)}</div></WorkspaceCard>

        <WorkspaceCard title="Reassessment" subtitle="Atlas reassesses only when new reviewed evidence exists; prior reviews remain unchanged."><form action={requestAtlasReassessmentAction} className="grid gap-2"><Hidden id={opportunityId}/><input name="reason" required maxLength={1000} className={field} placeholder="Why should Atlas reassess now?"/><button className={`${button} disabled:cursor-not-allowed disabled:bg-[#a8adb1]`} disabled={!newReviewedEvidence.length}>Request reassessment</button></form><p className="mt-3 text-xs text-[#6f757b]">{newReviewedEvidence.length ? `${newReviewedEvidence.length} new reviewed evidence item${newReviewedEvidence.length === 1 ? "" : "s"} ready` : "Review new evidence to enable reassessment"} · {workspace.reassessments.length} completed</p></WorkspaceCard>
      </div>

      <details className="mt-5 rounded-2xl border border-[#e3e5e6] bg-white p-5"><summary className="cursor-pointer font-semibold">Immutable decision timeline · {workspace.timeline.length} events</summary><ol className="mt-4 space-y-3 border-l border-[#d9dcde] pl-4">{[...workspace.timeline].reverse().map((item) => <li key={item.id} className="text-sm"><p className="font-medium">{item.type}</p><p className="text-[#626970]">{item.description}</p><p className="mt-1 text-xs text-[#8a9095]">{new Date(item.at).toLocaleString("en")} · {item.actor}</p></li>)}</ol></details>
    </div>
  </section>;
}

function Hidden({ id }: { id: string }) { return <input type="hidden" name="opportunityId" value={id}/>; }
function WorkspaceCard({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <section className="rounded-2xl border border-[#e3e5e6] bg-white p-5"><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs leading-5 text-[#6f757b]">{subtitle}</p><div className="mt-4">{children}</div></section>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#e3e5e6] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#7a8086]">{label}</p><p className="mt-2 text-sm leading-6">{value}</p></div>; }
function List({ title, items, empty }: { title: string; items: readonly string[]; empty: string }) { return <div><h3 className="text-sm font-semibold">{title}</h3>{items.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-[#626970]">{[...new Set(items)].map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-[#6f757b]">{empty}</p>}</div>; }
