import Link from "next/link";
import { AtlasMark } from "@/components/atlas/atlas-mark";
import { StatusBadge } from "@/components/status-badge";
import type { ExecutiveOpportunityIntelligence } from "@/lib/opportunity-intelligence";
import type { Opportunity } from "@/types/opportunity";
import { finalizeCollectedOpportunityDecision, selectCollectedOpportunityDecision } from "@/app/opportunities/actions";
import { toPlainText } from "@/lib/plain-text";
import type { Locale } from "@/lib/locale";
import type { ReactNode } from "react";
import { OpportunityApplicationLink } from "./opportunity-application-link";
import { resolvePublishedCompensation } from "@/lib/discovery/published-compensation";

type DecisionState = { action?: "Pursue" | "Watch" | "Skip"; status?: "Finalized"; finalizedAt?: string };

export function CollectedOpportunityIntelligence({ opportunity, intelligence, decisionNotice, idempotencyKey }: { opportunity: Opportunity; intelligence: ExecutiveOpportunityIntelligence; decisionNotice?: string; idempotencyKey: string; locale?: Locale }) {
  const draft = (opportunity as Opportunity & { executiveDecisionDraft?: DecisionState }).executiveDecisionDraft;
  const finalDecision = (opportunity as Opportunity & { executiveDecision?: DecisionState }).executiveDecision;
  const compensation = resolvePublishedCompensation(opportunity);
  const salary = compensation?.minimum !== undefined || compensation?.maximum !== undefined ? `${compensation.currency ?? "Currency unconfirmed"} ${compensation.minimum?.toLocaleString("en-GB") ?? "?"}${compensation.maximum !== undefined ? `–${compensation.maximum.toLocaleString("en-GB")}` : ""}` : "Not listed";
  const roleSummary = opportunity.summary ? toPlainText(opportunity.summary) : "The employer has not provided a complete role summary.";
  const expectedImpact = opportunity.keyResponsibilities.length ? opportunity.keyResponsibilities.slice(0, 3) : [];
  const leadershipExpectations = opportunity.keyResponsibilities.filter((item) => /lead|manage|direct|own|executive|board|strategy/i.test(item));

  return <main className="mx-auto max-w-6xl px-5 py-8 text-[#17191c] sm:px-6 lg:px-10">
    <nav className="flex flex-wrap gap-4 text-sm"><Link href="/opportunities" className="text-[#536f80] hover:underline">← Back to jobs</Link></nav>
    <header className="mt-6 border-b border-[#e3e5e6] pb-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><Link href={`/companies/${encodeURIComponent(opportunity.companyName)}`} className="text-sm font-medium text-[#536f80] hover:underline">{opportunity.companyName} →</Link><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">{opportunity.jobTitle}</h1><p className="mt-3 text-[#6f757b]">{opportunity.location} · {opportunity.workArrangement} · {opportunity.employmentType}</p></div><OpportunityApplicationLink opportunity={opportunity} className="inline-flex min-h-11 shrink-0 items-center justify-center rounded-xl bg-[#17191c] px-5 py-3 text-sm font-semibold text-white hover:bg-black"/></div><div className="mt-5 flex flex-wrap gap-2"><StatusBadge tone={intelligence.recommendation === "Prioritize" ? "success" : "info"}>{intelligence.recommendation === "Prioritize" ? "Recommended by Atlas" : "Atlas review available"}</StatusBadge><StatusBadge tone="neutral">Updated {intelligence.freshness.ageHours ?? "?"}h ago</StatusBadge>{opportunity.verificationStatus && <StatusBadge tone={opportunity.verificationStatus === "Employer source matched" ? "success" : "warning"}>{opportunity.verificationStatus}</StatusBadge>}</div>{opportunity.verificationStatus === "Unverified LinkedIn observation" && <p className="mt-5 max-w-3xl rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900">This private observation came from details you supplied. Confirm it against the employer’s application page before acting on it.</p>}</header>

    {decisionNotice === "selected" && <p role="status" className="mt-6 rounded-xl border border-[#bfd0d9] bg-[#edf3f5] px-4 py-3 text-sm text-[#36576a]">{draft?.action} selected. You can change this before confirming.</p>}
    {decisionNotice === "complete" && <p role="status" className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Decision saved. Your Home and Applications views now reflect it.</p>}

    <section className="mt-7 overflow-hidden rounded-3xl border border-[#cfdde3] bg-[linear-gradient(135deg,#f4f8f9_0%,#ffffff_60%)] shadow-[0_18px_55px_rgba(34,54,64,.08)]">
      <div className="grid gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_230px]"><div><div className="flex items-center gap-3"><AtlasMark size={44}/><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6f8796]">Atlas executive briefing</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.025em]">{intelligence.recommendation === "Prioritize" ? "This opportunity deserves attention" : intelligence.recommendation === "Deprioritize" ? "Proceed only if the conflicts change" : "Investigate before committing time"}</h2></div></div><p className="mt-5 max-w-3xl text-base leading-7 text-[#53616a]">{intelligence.guidance}</p></div><div className="rounded-2xl border border-[#dbe4e7] bg-white/90 p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#7a858b]">Recommendation</p><p className="mt-2 text-xl font-semibold">{intelligence.recommendation}</p><p className="mt-3 text-sm text-[#626970]">Confidence {intelligence.atlasConfidence.score}% · {intelligence.atlasConfidence.level}</p><p className="mt-2 text-xs leading-5 text-[#7a8086]">Confidence measures evidence coverage, not certainty.</p></div></div>
      <div className="grid border-t border-[#dfe7ea] bg-white/75 md:grid-cols-3"><BriefingList title="Strengths" items={intelligence.strengths} empty="No profile-backed strength is confirmed yet."/><BriefingList title="Risks" items={intelligence.concerns} empty="No material risk is supported by current evidence."/><BriefingList title="Unknowns to investigate" items={intelligence.missingInformation} empty="No decision-critical information gap detected."/></div>
      <div className="border-t border-[#dfe7ea] bg-[#f8fafb] px-6 py-5 sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#6f8796]">Next suggested action</p><p className="mt-2 text-sm leading-6 text-[#53616a]">{intelligence.missingInformation.length ? `Confirm ${intelligence.missingInformation.slice(0, 2).join(" and ").toLowerCase()} before choosing Pursue.` : "Review the role responsibilities, then choose Pursue, Watch, or Skip."}</p></div>
    </section>

    <div className="mt-7 grid min-w-0 gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="min-w-0 space-y-6">
      <ReviewSection eyebrow="Role" title="Role summary"><p className="whitespace-pre-line break-words text-sm leading-7 text-[#626970] [overflow-wrap:anywhere]">{roleSummary}</p><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><Definition label="Location" value={opportunity.location}/><Definition label="Work model" value={opportunity.workArrangement}/><Definition label="Employment" value={opportunity.employmentType}/><Definition label="Compensation" value={salary}/></dl></ReviewSection>
      <ReviewSection eyebrow="Responsibilities" title="What the executive will own"><List title="Published responsibilities" items={opportunity.keyResponsibilities} empty="Responsibilities are not confirmed in the current source."/></ReviewSection>
      <ReviewSection eyebrow="Business impact" title="Expected impact"><List title="Impact supported by the published role" items={expectedImpact} empty="The source does not state measurable business impact."/></ReviewSection>
      <ReviewSection eyebrow="Leadership" title="Leadership expectations"><List title="Leadership evidence" items={leadershipExpectations} empty="Leadership scope is not explicit in the current source."/></ReviewSection>
      <ReviewSection eyebrow="Career opportunity" title="Why this role may matter"><p className="text-sm leading-7 text-[#626970]">{intelligence.guidance}</p></ReviewSection>
      <ReviewSection eyebrow="Capabilities" title="Required capabilities"><div className="grid gap-5 md:grid-cols-2"><List title="Required" items={opportunity.requiredSkills} empty="Required capabilities are not listed."/><List title="Preferred" items={opportunity.preferredSkills} empty="Preferred capabilities are not listed."/></div></ReviewSection>
      <ReviewSection eyebrow="Company analysis" title={opportunity.companyName}><dl className="grid gap-4 text-sm sm:grid-cols-2"><Definition label="Industry" value={opportunity.industry || "Unknown"}/><Definition label="Company scale" value={opportunity.companySize || "Unknown"}/><Definition label="Employer intelligence" value={opportunity.companyProfile?.evidenceStatus ?? "Unknown"}/><Definition label="Growth and financials" value="Not established by current evidence"/></dl><Link href={`/companies/${encodeURIComponent(opportunity.companyName)}`} className="mt-5 inline-flex rounded-xl border border-[#d9dcde] px-4 py-2.5 text-sm font-semibold text-[#36576a] hover:bg-[#f7f8f8]">Open company briefing →</Link></ReviewSection>
      <details className="rounded-2xl border border-[#e3e5e6] bg-white p-6"><summary className="cursor-pointer text-lg font-semibold">Evidence, provenance, and open questions</summary><div className="mt-6 space-y-6"><div><h3 className="font-semibold">What is known</h3><div className="mt-3 space-y-3">{intelligence.evidence.map((item, index) => <article key={`${item.label}-${index}`} className="rounded-xl bg-[#f7f8f8] p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.label}</p><p className="mt-1 text-sm text-[#626970]">{item.value}</p></div><StatusBadge tone={item.certainty === "Confirmed" ? "success" : item.certainty === "Estimated" ? "info" : "neutral"}>{item.certainty}</StatusBadge></div></article>)}</div></div><List title="Questions requiring investigation" items={intelligence.missingInformation.map((item) => `What evidence can confirm ${item.toLowerCase()}?`)} empty="No decision-critical investigation is currently identified."/><p className="text-xs text-[#7a8086]">Sources: {intelligence.provenance.map((source) => source.name).join(" · ") || "No attributable source available"}</p></div></details>
    </div><DecisionPanel opportunity={opportunity} draft={draft} finalDecision={finalDecision} idempotencyKey={idempotencyKey}/></div>
  </main>;
}

function DecisionPanel({ opportunity, draft, finalDecision, idempotencyKey }: { opportunity: Opportunity; draft?: DecisionState; finalDecision?: DecisionState; idempotencyKey: string }) {
  return <aside className="space-y-6"><section className="sticky top-24 rounded-2xl border border-[#e3e5e6] bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">What would you like to do?</h2><div className="mt-4"><OpportunityApplicationLink opportunity={opportunity} className="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-[#17191c] px-4 py-3 text-sm font-semibold text-white hover:bg-black"/></div>{finalDecision?.status === "Finalized" ? <div className="mt-4"><StatusBadge tone="success">{finalDecision.action} · Saved</StatusBadge><p className="mt-3 text-sm text-[#626970]">Your decision and the information available at the time have been preserved.</p><Link href="/applications" className="mt-5 inline-flex text-sm font-semibold text-[#536f80]">View applications →</Link></div> : <><p className="mt-4 text-sm leading-6 text-[#6f757b]">Choose a direction. You can change it until you confirm.</p><div className="mt-5 grid gap-2">{(["Pursue", "Watch", "Skip"] as const).map((action) => <form key={action} action={selectCollectedOpportunityDecision}><input type="hidden" name="opportunityId" value={opportunity.id}/><input type="hidden" name="decision" value={action}/><button type="submit" aria-pressed={draft?.action === action} className={`w-full rounded-xl border px-4 py-3 text-left text-sm font-semibold transition ${draft?.action === action ? "border-[#55778a] bg-[#edf3f5] text-[#36576a]" : "border-[#d9dcde] hover:-translate-y-px hover:bg-[#f7f8f8]"}`}>{action}{action === "Watch" ? " (save for later)" : ""}</button></form>)}</div>{draft?.action && <form action={finalizeCollectedOpportunityDecision} className="mt-4"><input type="hidden" name="opportunityId" value={opportunity.id}/><input type="hidden" name="decision" value={draft.action}/><input type="hidden" name="idempotencyKey" value={idempotencyKey}/><button type="submit" className="w-full rounded-xl bg-[#17191c] px-4 py-3 text-sm font-semibold text-white transition hover:-translate-y-px hover:bg-black">Confirm {draft.action}</button></form>}</>}</section></aside>;
}

function ReviewSection({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <section className="rounded-2xl border border-[#e3e5e6] bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#936b3f]">{eyebrow}</p><h2 className="mt-2 text-xl font-semibold">{title}</h2><div className="mt-4">{children}</div></section>; }
function BriefingList({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <div className="p-6 sm:px-8"><h3 className="text-sm font-semibold">{title}</h3>{items.length ? <ul className="mt-3 space-y-2 text-sm leading-6 text-[#626970]">{items.slice(0, 3).map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="mt-3 text-sm leading-6 text-[#7a8086]">{empty}</p>}</div>; }
function List({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <div><h3 className="font-semibold">{title}</h3>{items.length ? <ul className="mt-2 list-disc space-y-2 pl-5 text-sm leading-6 text-[#626970]">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-[#6f757b]">{empty}</p>}</div>; }
function Definition({ label, value }: { label: string; value: string }) { return <div><dt className="text-[#7a8086]">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
