import Link from "next/link";
import { AtlasMark } from "@/components/atlas/atlas-mark";
import { StatusBadge } from "@/components/status-badge";
import type { ExecutiveOpportunityIntelligence } from "@/lib/opportunity-intelligence";
import type { Opportunity } from "@/types/opportunity";
import { finalizeCollectedOpportunityDecision, selectCollectedOpportunityDecision } from "@/app/opportunities/actions";
import { toPlainText } from "@/lib/plain-text";
import type { Locale } from "@/lib/locale";

type DecisionState = { action?: "Pursue" | "Watch" | "Skip"; status?: "Finalized"; finalizedAt?: string };

export function CollectedOpportunityIntelligence({ opportunity, intelligence, decisionNotice, idempotencyKey, locale = "en" }: { opportunity: Opportunity; intelligence: ExecutiveOpportunityIntelligence; decisionNotice?: string; idempotencyKey: string; locale?: Locale }) {
  const tr = locale === "tr";
  const draft = (opportunity as Opportunity & { executiveDecisionDraft?: DecisionState }).executiveDecisionDraft;
  const finalDecision = (opportunity as Opportunity & { executiveDecision?: DecisionState }).executiveDecision;
  const salary = opportunity.salaryMin || opportunity.salaryMax ? `${opportunity.salaryCurrency ?? ""} ${opportunity.salaryMin?.toLocaleString() ?? ""}${opportunity.salaryMax ? `–${opportunity.salaryMax.toLocaleString()}` : ""}`.trim() : (tr ? "Belirtilmemiş" : "Not listed");
  return <main className="mx-auto max-w-6xl px-5 py-8 text-[#17191c] sm:px-6 lg:px-10">
    <nav className="flex flex-wrap gap-4 text-sm"><Link href="/opportunities" className="text-[#536f80]">{tr ? "← İşlere dön" : "← Back to jobs"}</Link>{opportunity.sourceUrl && <a href={opportunity.sourceUrl} target="_blank" rel="noreferrer" className="text-[#536f80]">{tr ? "Orijinal ilan ↗" : "Original listing ↗"}</a>}</nav>
    <header className="mt-6 border-b border-[#e3e5e6] pb-8"><p className="text-sm font-medium text-[#536f80]">{opportunity.companyName}</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">{opportunity.jobTitle}</h1><p className="mt-3 text-[#6f757b]">{opportunity.location} · {opportunity.workArrangement} · {opportunity.employmentType}</p><div className="mt-5 flex flex-wrap gap-2"><StatusBadge tone={intelligence.recommendation === "Prioritize" ? "success" : "info"}>{intelligence.recommendation === "Prioritize" ? (tr ? "Atlas öneriyor" : "Recommended by Atlas") : (tr ? "Atlas incelemesi hazır" : "Atlas review available")}</StatusBadge><StatusBadge tone="neutral">{tr ? `${intelligence.freshness.ageHours ?? "?"} saat önce güncellendi` : `Updated ${intelligence.freshness.ageHours ?? "?"}h ago`}</StatusBadge>{opportunity.verificationStatus && <StatusBadge tone={opportunity.verificationStatus === "Employer source matched" ? "success" : "warning"}>{tr ? opportunity.verificationStatus === "Employer source matched" ? "İşveren kaynağıyla eşleşti" : "Doğrulanmamış gözlem" : opportunity.verificationStatus}</StatusBadge>}</div>{opportunity.verificationStatus === "Unverified LinkedIn observation" && <p className="mt-5 max-w-3xl rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900">{tr ? "Bu özel gözlem, senin sağladığın ayrıntılardan oluşturuldu. Harekete geçmeden önce işverenin başvuru sayfasıyla doğrula." : "This private observation came from details you supplied. Confirm it against the employer’s application page before acting on it."}</p>}</header>

    {decisionNotice === "selected" && <p role="status" className="mt-6 rounded-xl border border-[#bfd0d9] bg-[#edf3f5] px-4 py-3 text-sm text-[#36576a]">{tr ? `${decisionLabel(draft?.action, true)} seçildi. Onaylamadan önce değiştirebilirsin.` : `${draft?.action} selected. You can change this before confirming.`}</p>}
    {decisionNotice === "complete" && <p role="status" className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{tr ? "Karar kaydedildi. Ana Sayfa ve Başvurular görünümleri artık bu kararı yansıtıyor." : "Decision saved. Your Home and Applications views now reflect it."}</p>}

    <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><section className="rounded-2xl border border-[#e3e5e6] bg-white p-6"><h2 className="text-xl font-semibold">{tr ? "Rol özeti" : "Role overview"}</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-[#626970]">{opportunity.summary ? toPlainText(opportunity.summary) : (tr ? "İşveren henüz eksiksiz bir rol özeti sağlamadı." : "The employer has not provided a complete role summary.")}</p><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><Definition label={tr ? "Şirket" : "Company"} value={opportunity.companyName}/><Definition label={tr ? "Konum" : "Location"} value={opportunity.location}/><Definition label={tr ? "Çalışma modeli" : "Work model"} value={opportunity.workArrangement}/><Definition label={tr ? "Ücret" : "Compensation"} value={salary}/></dl></section>
      <section className="rounded-2xl border border-[#dfe7ea] bg-[#f5f8f9] p-6"><div className="flex items-center gap-3"><AtlasMark size={40}/><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6f8796]">Atlas</p><h2 className="text-xl font-semibold">{tr ? "Bu rol neden dikkatimi çekti" : "Why this caught my attention"}</h2></div></div><p className="mt-4 leading-7 text-[#53616a]">{tr ? "Bu değerlendirme, yalnızca doğrulanmış rol bilgileriyle paylaşmayı seçtiğin kariyer bağlamını karşılaştırır. Aşağıdaki güçlü yönleri, kaygıları ve açık soruları kararından önce incele." : intelligence.guidance}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><List title={tr ? "Neden uygun olabilir" : "Why it may fit"} items={intelligence.strengths} empty={tr ? "Henüz bir güçlü yön belirlemek için yeterli doğrulanmış profil bilgisi yok." : "I do not yet have enough confirmed profile evidence to name a strength."}/><List title={tr ? "Kontrol edilmesi gereken nokta" : "One thing to check"} items={intelligence.concerns} empty={tr ? "Mevcut kanıtların desteklediği belirgin bir kaygı yok." : "No clear concern is supported by the available evidence."}/></div></section>
      <details className="rounded-2xl border border-[#e3e5e6] bg-white p-6"><summary className="cursor-pointer text-lg font-semibold">{tr ? "Ayrıntılı kanıtları ve açık soruları gör" : "See detailed evidence and open questions"}</summary><div className="mt-6 space-y-6"><div><h3 className="font-semibold">{tr ? "Bilinenler" : "What is known"}</h3><div className="mt-3 space-y-3">{intelligence.evidence.map((item, index) => <article key={`${item.label}-${index}`} className="rounded-xl bg-[#f7f8f8] p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.label}</p><p className="mt-1 text-sm text-[#626970]">{item.value}</p></div><StatusBadge tone={item.certainty === "Confirmed" ? "success" : item.certainty === "Estimated" ? "info" : "neutral"}>{tr ? item.certainty === "Confirmed" ? "Doğrulandı" : item.certainty === "Estimated" ? "Tahmini" : "Bilinmiyor" : item.certainty}</StatusBadge></div></article>)}</div></div><List title={tr ? "Bilinmeyenler" : "What remains unknown"} items={intelligence.missingInformation} empty={tr ? "Kararı etkileyen kritik bir bilgi açığı tespit edilmedi." : "No decision-critical gap was detected."}/><p className="text-xs text-[#7a8086]">{tr ? "Kaynaklar" : "Sources"}: {intelligence.provenance.map((source) => source.name).join(" · ") || (tr ? "Atfedilebilir kaynak yok" : "No attributable source available")}</p></div></details>
    </div><aside className="space-y-6"><section className="sticky top-24 rounded-2xl border border-[#e3e5e6] bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">{tr ? "Ne yapmak istersin?" : "What would you like to do?"}</h2>{finalDecision?.status === "Finalized" ? <div className="mt-4"><StatusBadge tone="success">{decisionLabel(finalDecision.action, tr)} · {tr ? "Kaydedildi" : "Saved"}</StatusBadge><p className="mt-3 text-sm text-[#626970]">{tr ? "Kararın ve o anda mevcut olan bilgiler korundu." : "Your decision and the information available at the time have been preserved."}</p><Link href="/applications" className="mt-5 inline-flex text-sm font-semibold text-[#536f80]">{tr ? "Başvuruları gör →" : "View applications →"}</Link></div> : <><p className="mt-2 text-sm leading-6 text-[#6f757b]">{tr ? "Bir yön seç. Onaylayana kadar değiştirebilirsin." : "Choose a direction. You can change it until you confirm."}</p><div className="mt-5 grid gap-2">{(["Pursue", "Watch", "Skip"] as const).map((action) => <form key={action} action={selectCollectedOpportunityDecision}><input type="hidden" name="opportunityId" value={opportunity.id}/><input type="hidden" name="decision" value={action}/><button type="submit" aria-pressed={draft?.action === action} className={`w-full rounded-xl border px-4 py-3 text-left text-sm font-semibold ${draft?.action === action ? "border-[#55778a] bg-[#edf3f5] text-[#36576a]" : "border-[#d9dcde] hover:bg-[#f7f8f8]"}`}>{decisionLabel(action, tr)}{action === "Watch" ? (tr ? " (sonra incele)" : " (save for later)") : ""}</button></form>)}</div>{draft?.action && <form action={finalizeCollectedOpportunityDecision} className="mt-4"><input type="hidden" name="opportunityId" value={opportunity.id}/><input type="hidden" name="decision" value={draft.action}/><input type="hidden" name="idempotencyKey" value={idempotencyKey}/><button type="submit" className="w-full rounded-xl bg-[#17191c] px-4 py-3 text-sm font-semibold text-white">{tr ? `${decisionLabel(draft.action, true)} kararını onayla` : `Confirm ${draft.action}`}</button></form>}</>}</section></aside></div>
  </main>;
}

function List({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <div><h3 className="font-semibold">{title}</h3>{items.length ? <ul className="mt-2 list-disc space-y-2 pl-5 text-sm leading-6 text-[#626970]">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-[#6f757b]">{empty}</p>}</div>; }
function Definition({ label, value }: { label: string; value: string }) { return <div><dt className="text-[#7a8086]">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
function decisionLabel(action: DecisionState["action"], tr: boolean) { if (!action || !tr) return action; return action === "Pursue" ? "İlerle" : action === "Watch" ? "Takip et" : "Geç"; }
