"use client";

type Action = (formData: FormData) => void | Promise<void>;

export function LinkedInImportPanel({ linkedInAction, alertAction, notice, message, verification, resetKey }: { linkedInAction: Action; alertAction: Action; notice?: string; message?: string; verification?: string; resetKey?: string }) {
  return <section id="linkedin-import" className="mt-5 scroll-mt-24 rounded-2xl border border-[#dfe2e3] bg-[#f8f9f9] p-5">
    <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#536f80]">Private import</p><h3 className="mt-1 text-lg font-semibold text-[#17191c]">Import from LinkedIn</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-[#626970]">Paste a LinkedIn job URL. Orendalis never signs in to LinkedIn, fetches the page, or stores LinkedIn credentials. Add visible details or the employer application URL to improve verification.</p></div><span className="w-fit rounded-full border border-[#d8dcde] bg-white px-3 py-1 text-xs font-medium text-[#626970]">You control every import</span></div>
    <form key={`linkedin-${resetKey ?? "initial"}`} action={linkedInAction} className="mt-5 grid gap-4 lg:grid-cols-2">
      <label className="text-sm font-medium text-[#30343a]">LinkedIn job URL<input name="linkedinUrl" type="url" required inputMode="url" placeholder="https://www.linkedin.com/jobs/view/1234567890" className="mt-2 w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm text-[#17191c] placeholder:text-[#9aa0a5]" /></label>
      <label className="text-sm font-medium text-[#30343a]">Employer or ATS application URL <span className="font-normal text-[#858b90]">(optional)</span><input name="employerUrl" type="url" inputMode="url" placeholder="https://company.com/careers/role" className="mt-2 w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm text-[#17191c] placeholder:text-[#9aa0a5]" /></label>
      <label className="text-sm font-medium text-[#30343a] lg:col-span-2">Visible job details <span className="font-normal text-[#858b90]">(optional)</span><textarea name="visibleDetails" rows={6} placeholder={"Title: Chief Revenue Officer\nCompany: Example Company\nLocation: London\n\nPaste only details you can lawfully view and choose to save."} className="mt-2 w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm leading-6 text-[#17191c] placeholder:text-[#9aa0a5]" /></label>
      <label className="flex items-start gap-3 text-sm leading-6 text-[#565c62] lg:col-span-2"><input name="consent" value="yes" type="checkbox" required className="mt-1 h-4 w-4 rounded border-[#c9cdcf]" /><span>I chose to import this job and any pasted details into my private Orendalis workspace.</span></label>
      <div className="lg:col-span-2"><button className="rounded-xl bg-[#17191c] px-5 py-3 text-sm font-semibold text-white hover:bg-black">Import job</button></div>
    </form>
    <details className="mt-5 border-t border-[#e2e5e6] pt-4"><summary className="cursor-pointer text-sm font-semibold text-[#536f80]">Import a LinkedIn job-alert email</summary><p className="mt-3 text-sm leading-6 text-[#626970]">Paste the alert email you received. Orendalis extracts only LinkedIn job links after your explicit consent; it does not connect to or monitor your mailbox.</p><form key={`alert-${resetKey ?? "initial"}`} action={alertAction} className="mt-4 space-y-4"><textarea name="alertText" required rows={7} placeholder="Paste the LinkedIn job-alert email here" className="w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm leading-6 text-[#17191c] placeholder:text-[#9aa0a5]" /><label className="flex items-start gap-3 text-sm leading-6 text-[#565c62]"><input name="consent" value="yes" type="checkbox" required className="mt-1 h-4 w-4 rounded border-[#c9cdcf]" /><span>I consent to importing the job links in this alert into my private workspace.</span></label><button className="rounded-xl border border-[#cfd3d5] bg-white px-5 py-3 text-sm font-semibold text-[#30343a] hover:bg-[#f2f3f3]">Import alert</button></form></details>
    {notice && <p role="status" className={`mt-5 rounded-xl border px-4 py-3 text-sm ${notice === "complete" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-rose-200 bg-rose-50 text-rose-800"}`}>{notice === "complete" ? verification === "Employer source matched" ? "Imported and matched to an employer-controlled record. LinkedIn is preserved as the discovery source." : "Imported privately as an unverified LinkedIn observation. Add the employer application URL later to verify and refresh it." : message ?? "That LinkedIn job could not be imported safely."}</p>}
  </section>;
}
