"use client";

import type { Locale } from "@/lib/locale";

type Action = (formData: FormData) => void | Promise<void>;

export function LinkedInImportPanel({ linkedInAction, alertAction, notice, message, verification, resetKey, locale = "en" }: { linkedInAction: Action; alertAction: Action; notice?: string; message?: string; verification?: string; resetKey?: string; locale?: Locale }) {
  const tr = locale === "tr";
  return <section id="linkedin-import" className="mt-5 scroll-mt-24 rounded-2xl border border-[#dfe2e3] bg-[#f8f9f9] p-5">
    <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#536f80]">{tr ? "Özel içe aktarma" : "Private import"}</p><h3 className="mt-1 text-lg font-semibold text-[#17191c]">{tr ? "LinkedIn'den içe aktar" : "Import from LinkedIn"}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-[#626970]">{tr ? "Bir LinkedIn iş ilanı bağlantısı yapıştır. Orendalis LinkedIn hesabına giriş yapmaz, sayfayı otomatik çekmez ve LinkedIn kimlik bilgilerini saklamaz. Doğrulamayı güçlendirmek için görünen ayrıntıları veya işveren başvuru bağlantısını ekleyebilirsin." : "Paste a LinkedIn job URL. Orendalis never signs in to LinkedIn, fetches the page, or stores LinkedIn credentials. Add visible details or the employer application URL to improve verification."}</p></div><span className="w-fit rounded-full border border-[#d8dcde] bg-white px-3 py-1 text-xs font-medium text-[#626970]">{tr ? "Her içe aktarma senin kontrolünde" : "You control every import"}</span></div>
    <form key={`linkedin-${resetKey ?? "initial"}`} action={linkedInAction} className="mt-5 grid gap-4 lg:grid-cols-2">
      <label className="text-sm font-medium text-[#30343a]">{tr ? "LinkedIn iş ilanı bağlantısı" : "LinkedIn job URL"}<input name="linkedinUrl" type="url" required inputMode="url" placeholder="https://www.linkedin.com/jobs/view/1234567890" className="mt-2 w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm text-[#17191c] placeholder:text-[#9aa0a5]" /></label>
      <label className="text-sm font-medium text-[#30343a]">{tr ? "İşveren veya ATS başvuru bağlantısı" : "Employer or ATS application URL"} <span className="font-normal text-[#858b90]">{tr ? "(isteğe bağlı)" : "(optional)"}</span><input name="employerUrl" type="url" inputMode="url" placeholder="https://company.com/careers/role" className="mt-2 w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm text-[#17191c] placeholder:text-[#9aa0a5]" /></label>
      <label className="text-sm font-medium text-[#30343a] lg:col-span-2">{tr ? "Görünen iş ayrıntıları" : "Visible job details"} <span className="font-normal text-[#858b90]">{tr ? "(isteğe bağlı)" : "(optional)"}</span><textarea name="visibleDetails" rows={6} placeholder={tr ? "Pozisyon: Gelir Direktörü\nŞirket: Örnek Şirket\nKonum: İstanbul\n\nYalnızca yasal olarak görebildiğin ve kaydetmeyi seçtiğin ayrıntıları yapıştır." : "Title: Chief Revenue Officer\nCompany: Example Company\nLocation: London\n\nPaste only details you can lawfully view and choose to save."} className="mt-2 w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm leading-6 text-[#17191c] placeholder:text-[#9aa0a5]" /></label>
      <label className="flex items-start gap-3 text-sm leading-6 text-[#565c62] lg:col-span-2"><input name="consent" value="yes" type="checkbox" required className="mt-1 h-4 w-4 rounded border-[#c9cdcf]" /><span>{tr ? "Bu ilanı ve yapıştırdığım ayrıntıları özel Orendalis çalışma alanıma aktarmayı seçtim." : "I chose to import this job and any pasted details into my private Orendalis workspace."}</span></label>
      <div className="lg:col-span-2"><button className="rounded-xl bg-[#17191c] px-5 py-3 text-sm font-semibold text-white hover:bg-black">{tr ? "İlanı içe aktar" : "Import job"}</button></div>
    </form>
    <details className="mt-5 border-t border-[#e2e5e6] pt-4"><summary className="cursor-pointer text-sm font-semibold text-[#536f80]">{tr ? "LinkedIn iş uyarısı e-postasını içe aktar" : "Import a LinkedIn job-alert email"}</summary><p className="mt-3 text-sm leading-6 text-[#626970]">{tr ? "Aldığın uyarı e-postasını yapıştır. Orendalis yalnızca açık onayın sonrasında LinkedIn iş bağlantılarını çıkarır; posta kutuna bağlanmaz veya onu izlemez." : "Paste the alert email you received. Orendalis extracts only LinkedIn job links after your explicit consent; it does not connect to or monitor your mailbox."}</p><form key={`alert-${resetKey ?? "initial"}`} action={alertAction} className="mt-4 space-y-4"><textarea name="alertText" required rows={7} placeholder={tr ? "LinkedIn iş uyarısı e-postasını buraya yapıştır" : "Paste the LinkedIn job-alert email here"} className="w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm leading-6 text-[#17191c] placeholder:text-[#9aa0a5]" /><label className="flex items-start gap-3 text-sm leading-6 text-[#565c62]"><input name="consent" value="yes" type="checkbox" required className="mt-1 h-4 w-4 rounded border-[#c9cdcf]" /><span>{tr ? "Bu uyarıdaki iş bağlantılarının özel çalışma alanıma aktarılmasına onay veriyorum." : "I consent to importing the job links in this alert into my private workspace."}</span></label><button className="rounded-xl border border-[#cfd3d5] bg-white px-5 py-3 text-sm font-semibold text-[#30343a] hover:bg-[#f2f3f3]">{tr ? "Uyarıyı içe aktar" : "Import alert"}</button></form></details>
    {notice && <p role="status" className={`mt-5 rounded-xl border px-4 py-3 text-sm ${notice === "complete" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-rose-200 bg-rose-50 text-rose-800"}`}>{notice === "complete" ? verification === "Employer source matched" ? (tr ? "İçe aktarıldı ve işveren tarafından yönetilen kayıtla eşleştirildi. LinkedIn keşif kaynağı olarak korundu." : "Imported and matched to an employer-controlled record. LinkedIn is preserved as the discovery source.") : (tr ? "Doğrulanmamış bir LinkedIn gözlemi olarak özel biçimde içe aktarıldı. Doğrulamak ve yenilemek için işveren başvuru bağlantısını daha sonra ekleyebilirsin." : "Imported privately as an unverified LinkedIn observation. Add the employer application URL later to verify and refresh it.") : message ?? (tr ? "Bu LinkedIn ilanı güvenli biçimde içe aktarılamadı." : "That LinkedIn job could not be imported safely.")}</p>}
  </section>;
}
