import { PageHeader } from "@/components/page-header";
import { SecondaryButton } from "@/components/secondary-button";
import { SectionCard } from "@/components/section-card";
import { LinkedInImportPanel } from "./linkedin-import-panel";
import type { Locale } from "@/lib/locale";

export function OpportunityUniverseEmpty({ collectionAction, linkedInAction, alertAction, linkedInNotice, message, locale = "en", cvComplete, savedRoles, newRoles }: { collectionAction?: (formData: FormData) => void | Promise<void>; linkedInAction: (formData: FormData) => void | Promise<void>; alertAction: (formData: FormData) => void | Promise<void>; linkedInNotice?: string; message?: string; locale?: Locale; cvComplete?: boolean; savedRoles?: string; newRoles?: string }) {
  const tr = locale === "tr";
  return <div className="mx-auto max-w-6xl px-5 py-8 sm:px-6 lg:px-10"><PageHeader eyebrow={tr ? "İşler" : "Jobs"} title={tr ? "Bir sonraki yönetici rolünü bul" : "Find your next executive role"} description={tr ? "Fırsatları tek yerde ara. Atlas önem verdiğin noktaları zamanla öğrenir ve hangi rollerin ilgini hak ettiğini açıklar." : "Search opportunities in one place. Atlas will quietly learn what matters and explain which opportunities deserve attention."} actions={<SecondaryButton href="/import">{tr ? "CV'ni yükle" : "Upload your CV"}</SecondaryButton>} />{cvComplete && <p role="status" className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm leading-6 text-emerald-900">{tr ? `Deneyimin kaydedildi. ${savedRoles ?? "0"} rol onaylandı${newRoles !== undefined ? ` (${newRoles} yeni)` : ""}.` : `Your experience is saved. ${savedRoles ?? "0"} ${savedRoles === "1" ? "role is" : "roles are"} confirmed${newRoles !== undefined ? ` (${newRoles} newly added)` : ""}.`}</p>}<LinkedInImportPanel locale={locale} linkedInAction={linkedInAction} alertAction={alertAction} notice={linkedInNotice} message={message} /><SectionCard className="mt-8"><h2 className="text-xl font-semibold">{tr ? "Arama burada başlıyor" : "Search starts here"}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6f757b]">{tr ? "Kaynaklar bağlandıkça işler burada görünür. Şimdi bir şirket kariyer sayfası ekleyebilir veya Atlas'ın gelecekteki önerilerini hazırlaması için CV'ni yükleyebilirsin." : "Search opportunities in one place. Add a company career page now, or upload your CV so Atlas can prepare future recommendations."}</p>{collectionAction && <form action={collectionAction} className="mt-6 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="career-page-empty">{tr ? "Şirket kariyer sayfası" : "Company career page"}</label><input id="career-page-empty" name="board" required placeholder={tr ? "Şirket kariyer sayfası bağlantısını yapıştır" : "Paste a company career page URL"} className="min-w-64 flex-1 rounded-xl border border-[#d9dcde] bg-white px-4 py-2.5 text-sm text-[#17191c] placeholder:text-[#9aa0a5]"/><button className="rounded-xl bg-[#17191c] px-4 py-2.5 text-sm font-medium text-white">{tr ? "İşleri ekle" : "Add jobs"}</button></form>}</SectionCard></div>;
}
