import Link from "next/link";
import { AuthField, AuthFrame, FormMessage, SubmitButton } from "@/components/auth/auth-frame";
import { currentSession } from "@/lib/auth/session";
import { founderBootstrapStatus } from "@/lib/auth/founder-bootstrap";
import { founderSignInAction, founderSignUpAction, initializeFounderAction } from "./actions";

export default async function FounderBootstrapPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  const q=await searchParams; const session=await currentSession();
  if(!session)return <AuthFrame eyebrow="Secure one-time initialization" title="Establish the founding Workspace" description="This protected path creates the first verified founder identity and permanently closes after successful initialization."><FormMessage message={q.error}/><div className="space-y-8"><section><h2 className="text-lg font-semibold">Create the verified founder account</h2><form action={founderSignUpAction} className="mt-4 space-y-4"><AuthField label="Authorized founder email" name="email" type="email" autoComplete="email"/><AuthField label="New password" name="password" type="password" autoComplete="new-password"/><SubmitButton>Create founder account</SubmitButton></form></section><div className="border-t border-white/10"/><section><h2 className="text-lg font-semibold">Account already verified?</h2><form action={founderSignInAction} className="mt-4 space-y-4"><AuthField label="Founder email" name="email" type="email" autoComplete="email"/><AuthField label="Password" name="password" type="password" autoComplete="current-password"/><SubmitButton>Sign in securely</SubmitButton></form></section></div></AuthFrame>;
  const state=await founderBootstrapStatus(session.accessToken);
  if(state.status==="COMPLETE")return <AuthFrame eyebrow="Initialization complete" title="Founder control is ready" description="The founding identity, Workspace ownership, Career Memory foundations, and immutable audit event are established."><Link href="/company-control" className="block rounded-xl bg-white px-4 py-3 text-center text-sm font-semibold text-slate-950">Enter Company Control</Link></AuthFrame>;
  if(state.status!=="READY")return <AuthFrame eyebrow="Protected initialization" title="Founder bootstrap unavailable" description="This initialization path is closed, unconfigured, or not authorized for the current verified account."><FormMessage message={q.error??"No records were created. Contact the environment owner to review the protected bootstrap configuration."}/><Link href="/login" className="text-sm text-blue-300">Return to sign in</Link></AuthFrame>;
  return <AuthFrame eyebrow="Final authorization" title="Create the founding Career Memory" description="This atomic, one-time operation creates the founder identity, personal Workspace, Owner membership, empty Blueprint, Career Ledger context, Atlas context, settings, and immutable audit record."><FormMessage message={q.error}/><div className="rounded-xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm leading-6 text-amber-100"><strong>Permanent security boundary.</strong> After success, this route cannot initialize another founder. Invitations become the only path for additional users.</div><form action={initializeFounderAction} className="mt-6 space-y-5"><label className="flex items-start gap-3 rounded-xl border border-white/10 p-4 text-sm leading-6 text-slate-300"><input required name="atlasPromiseAccepted" type="checkbox" className="mt-1 accent-blue-500"/><span><strong className="text-white">I accept the Atlas Promise.</strong><br/>Atlas strengthens executive judgment, preserves evidence and history, explains recommendations, admits uncertainty, and leaves every career decision with the executive.</span></label><SubmitButton>Create founding Workspace</SubmitButton></form></AuthFrame>;
}
