import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { resolveAuthenticatedRepositoryContext } from "@/lib/auth/repository-context";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { archiveRoomAction, inviteMemberAction, invokeAtlasAction, postRoomMessageAction, toggleBookmarkAction, togglePinAction } from "../actions";

type Room={id:string;title:string;topic:string;status:string;is_temporary:boolean;closes_at?:string;created_at:string};
type Membership={executive_identity_id:string;display_name:string;role:string};
type Message={id:string;parent_message_id?:string;author_identity_id:string;body:string;message_kind:string;source_message_ids:string[];created_at:string};
type Pin={message_id:string}; type Bookmark={message_id:string};

export default async function RoomPage({params,searchParams}:{params:Promise<{roomId:string}>;searchParams:Promise<Record<string,string|undefined>>}) {
  const resolved=await resolveAuthenticatedRepositoryContext(); if(!resolved) redirect("/login?next=/rooms");
  const {roomId}=await params; if(!/^[0-9a-f-]{36}$/i.test(roomId)) notFound();
  const client=createServerSupabaseClient(resolved.accessToken);
  const [roomResponse,membersResponse,messagesResponse,pinsResponse,bookmarksResponse]=await Promise.all([
    client.request<Room[]>(`executive_rooms?select=id,title,topic,status,is_temporary,closes_at,created_at&id=eq.${roomId}&limit=1`),
    client.request<Membership[]>("rpc/get_room_member_directory",{method:"POST",body:JSON.stringify({target_room:roomId})}),
    client.request<Message[]>(`executive_room_messages?select=id,parent_message_id,author_identity_id,body,message_kind,source_message_ids,created_at&room_id=eq.${roomId}&archived_at=is.null&order=created_at.asc`),
    client.request<Pin[]>(`executive_room_pins?select=message_id&room_id=eq.${roomId}`),
    client.request<Bookmark[]>(`executive_room_bookmarks?select=message_id&room_id=eq.${roomId}&executive_identity_id=eq.${resolved.context.actorId}`),
  ]);
  const room=roomResponse.data?.[0]; if(!room) notFound();
  const members=membersResponse.data??[]; const messages=messagesResponse.data??[];
  const names=new Map(members.map(member=>[member.executive_identity_id,member.display_name]));
  const myRole=members.find(member=>member.executive_identity_id===resolved.context.actorId)?.role;
  const pinned=new Set((pinsResponse.data??[]).map(pin=>pin.message_id)); const bookmarked=new Set((bookmarksResponse.data??[]).map(bookmark=>bookmark.message_id));
  const notice=(await searchParams).notice; const canModerate=myRole==="Owner"||myRole==="Moderator";

  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-6 lg:px-10"><div className="mb-5"><Link href="/rooms" className="text-sm font-semibold text-[#526a86] hover:underline">← All Executive Rooms</Link></div>
    <PageHeader eyebrow={`${room.status} · ${myRole ?? "Member"}`} title={room.title} description={room.topic}/>
    {notice&&<p role="status" className="mt-6 rounded-xl border border-[#b9d9c3] bg-[#edf8f0] px-4 py-3 text-sm text-[#285a37]">{notice}</p>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_19rem]">
      <section id="discussion"><div className="rounded-2xl border border-[#dfe5ee] bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="atlas-kicker">Discussion</p><h2 className="mt-2 text-2xl font-semibold">Shared decision record</h2></div><span className="rounded-full bg-[#f1f4f7] px-3 py-1 text-xs font-semibold">{messages.length} messages</span></div>
        {messages.length ? <div className="mt-6 space-y-4">{messages.map(message=><article key={message.id} className={`rounded-2xl border p-5 ${message.message_kind==="Atlas"?"border-[#a9c0d8] bg-[#f3f7fb]":"border-[#e2e6ea] bg-white"}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="font-semibold">{message.message_kind==="Atlas"?"Atlas":names.get(message.author_identity_id)??"Verified executive"}</span>{pinned.has(message.id)&&<span className="rounded-full bg-[#fff1cf] px-2 py-1 text-[11px] font-semibold text-[#77520e]">Pinned</span>}</div><time className="text-xs text-[#7a8592]">{formatDate(message.created_at)}</time></div>{message.parent_message_id&&<p className="mt-2 text-xs font-semibold text-[#63758b]">Reply in this discussion</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-[#344152]">{message.body}</p>{message.message_kind==="Atlas"&&message.source_message_ids.length>0&&<p className="mt-3 text-xs text-[#63758b]">Sources preserved: {message.source_message_ids.length} room messages</p>}<div className="mt-4 flex flex-wrap gap-2"><a href={`#reply-${message.id}`} className="rounded-full border border-[#cbd3dc] px-3 py-1.5 text-xs font-semibold">Reply</a><form action={toggleBookmarkAction}><input type="hidden" name="roomId" value={room.id}/><input type="hidden" name="messageId" value={message.id}/><button className="rounded-full border border-[#cbd3dc] px-3 py-1.5 text-xs font-semibold">{bookmarked.has(message.id)?"Remove bookmark":"Bookmark"}</button></form>{canModerate&&<form action={togglePinAction}><input type="hidden" name="roomId" value={room.id}/><input type="hidden" name="messageId" value={message.id}/><button className="rounded-full border border-[#cbd3dc] px-3 py-1.5 text-xs font-semibold">{pinned.has(message.id)?"Unpin":"Pin"}</button></form>}</div><form id={`reply-${message.id}`} action={postRoomMessageAction} className="mt-3 flex gap-2"><input type="hidden" name="roomId" value={room.id}/><input type="hidden" name="replyTo" value={message.id}/><label className="sr-only" htmlFor={`reply-input-${message.id}`}>Reply</label><input id={`reply-input-${message.id}`} name="body" required maxLength={4000} placeholder="Write a focused reply" className="min-w-0 flex-1 rounded-full border border-[#cbd3dc] px-4 py-2 text-sm"/><button className="rounded-full bg-[#1c2d45] px-4 py-2 text-sm font-semibold text-white">Send</button></form></article>)}</div>:<div className="mt-6 rounded-2xl border border-dashed border-[#cbd3dc] bg-[#f8fafc] p-8 text-center"><h3 className="text-lg font-semibold">Start with the decision</h3><p className="mt-2 text-sm text-[#5f6b7a]">Share the first fact, question, or trade-off. Atlas will not enter unless a member asks.</p></div>}
        {room.status==="Active"&&<form action={postRoomMessageAction} className="mt-6 border-t border-[#e5e9ed] pt-6"><input type="hidden" name="roomId" value={room.id}/><label htmlFor="room-message" className="text-sm font-semibold">Add to the discussion</label><textarea id="room-message" name="body" required maxLength={4000} rows={4} className="mt-2 w-full rounded-xl border border-[#cbd3dc] px-4 py-3" placeholder="Share evidence, a question, or a proposed next step."/><div className="mt-3 flex justify-end"><button className="rounded-full bg-[#0b1220] px-5 py-2.5 text-sm font-semibold text-white">Post message</button></div></form>}
      </div></section>
      <aside className="space-y-5"><section className="rounded-2xl border border-[#a9c0d8] bg-[#f3f7fb] p-5"><p className="atlas-kicker">Atlas on request</p><h2 className="mt-2 text-xl font-semibold">Ask, then verify</h2><p className="mt-2 text-sm leading-6 text-[#526070]">Atlas is not monitoring this room. A request cites the room messages it uses and never trains on this discussion.</p>{room.status==="Active"&&<form action={invokeAtlasAction} className="mt-4"><input type="hidden" name="roomId" value={room.id}/><label className="sr-only" htmlFor="atlas-request">Atlas request</label><textarea id="atlas-request" name="request" required minLength={3} maxLength={500} rows={3} className="w-full rounded-xl border border-[#b9c8d8] bg-white px-3 py-2 text-sm" placeholder="Summarize the decision and unresolved questions."/><button className="mt-3 w-full rounded-full bg-[#244b73] px-4 py-2.5 text-sm font-semibold text-white">Ask Atlas explicitly</button></form>}</section>
        <section className="rounded-2xl border border-[#dfe5ee] bg-white p-5"><p className="atlas-kicker">Members</p><h2 className="mt-2 text-xl font-semibold">{members.length} verified {members.length===1?"executive":"executives"}</h2><ul className="mt-4 space-y-3">{members.map(member=><li key={member.executive_identity_id} className="flex items-center justify-between gap-3 text-sm"><span>{names.get(member.executive_identity_id)??"Verified executive"}</span><span className="text-xs font-semibold text-[#63758b]">{member.role}</span></li>)}</ul>{myRole==="Owner"&&room.status==="Active"&&<form action={inviteMemberAction} className="mt-5 border-t border-[#e5e9ed] pt-5"><input type="hidden" name="roomId" value={room.id}/><label className="text-sm font-semibold">Invite a verified executive<input name="email" type="email" required className="mt-2 w-full rounded-xl border border-[#cbd3dc] px-3 py-2 font-normal" placeholder="name@company.com"/></label><select name="role" className="mt-3 w-full rounded-xl border border-[#cbd3dc] px-3 py-2 text-sm"><option>Participant</option><option>Moderator</option></select><button className="mt-3 w-full rounded-full border border-[#9eb3ca] px-4 py-2 text-sm font-semibold">Send private invitation</button></form>}</section>
        <section className="rounded-2xl border border-[#dfe5ee] bg-white p-5 text-sm text-[#5f6b7a]"><p><strong className="text-[#0b1220]">Privacy:</strong> invitation-only, no public discovery.</p><p className="mt-2"><strong className="text-[#0b1220]">Retention:</strong> 90-day bounded archive window.</p>{room.is_temporary&&<p className="mt-2"><strong className="text-[#0b1220]">Closes:</strong> {formatDate(room.closes_at)}</p>}{myRole==="Owner"&&room.status==="Active"&&<form action={archiveRoomAction} className="mt-4"><input type="hidden" name="roomId" value={room.id}/><button className="text-sm font-semibold text-[#8b3c34] underline-offset-4 hover:underline">Archive this room</button></form>}</section>
      </aside>
    </div>
  </main>;
}
function formatDate(value?:string){if(!value)return"Not set";const date=new Date(value);return Number.isNaN(date.getTime())?"Not set":new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(date);}
