import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { resolveAuthenticatedRepositoryContext } from "@/lib/auth/repository-context";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { archiveRoomAction, clearRoomConversationAction, inviteMemberAction, invokeAtlasAction, postRoomMessageAction, toggleBookmarkAction, togglePinAction } from "../actions";
import { RoomPresenceHeartbeat } from "@/components/rooms/room-presence-heartbeat";
import { RoomInviteLinkManager } from "@/components/rooms/room-invite-link-manager";
import { RoomLiveRefresh } from "@/components/rooms/room-live-refresh";
import { RoomEnterToSend } from "@/components/rooms/room-enter-to-send";
import { currentSession } from "@/lib/auth/session";
import { resolveExecutiveDisplayName } from "@/lib/auth/executive-display-name";

type Room={id:string;title:string;topic:string;short_purpose:string;language_name:string;access_mode:"Open"|"InvitationOnly";room_type:string;status:string;is_temporary:boolean;closes_at?:string;created_at:string;permanence_status:string;platform_managed:boolean;operator_label?:string};
type Membership={executive_identity_id:string;display_name:string;role:string};
type Message={id:string;parent_message_id?:string;author_identity_id:string;body:string;message_kind:string;source_message_ids:string[];structured_context:Record<string,string>;created_at:string};
type Pin={message_id:string}; type Bookmark={message_id:string};
type JoinLink={id:string;status:string;expires_at:string;max_uses:number;use_count:number;created_at:string};

export default async function RoomPage({params,searchParams}:{params:Promise<{roomId:string}>;searchParams:Promise<Record<string,string|undefined>>}) {
  const resolved=await resolveAuthenticatedRepositoryContext(); if(!resolved) redirect("/login?next=/rooms");
  const session=await currentSession();
  const {roomId}=await params; if(!/^[0-9a-f-]{36}$/i.test(roomId)) notFound();
  const client=createServerSupabaseClient(resolved.accessToken);
  const [roomResponse,membersResponse,messagesResponse,pinsResponse,bookmarksResponse,linksResponse,founderResponse]=await Promise.all([
    client.request<Room[]>(`executive_rooms?select=id,title,topic,short_purpose,language_name,access_mode,room_type,status,is_temporary,closes_at,created_at,permanence_status,platform_managed,operator_label&id=eq.${roomId}&limit=1`),
    client.request<Membership[]>("rpc/get_room_member_directory",{method:"POST",body:JSON.stringify({target_room:roomId})}),
    client.request<Message[]>(`executive_room_messages?select=id,parent_message_id,author_identity_id,body,message_kind,source_message_ids,structured_context,created_at&room_id=eq.${roomId}&archived_at=is.null&order=created_at.asc`),
    client.request<Pin[]>(`executive_room_pins?select=message_id&room_id=eq.${roomId}`),
    client.request<Bookmark[]>(`executive_room_bookmarks?select=message_id&room_id=eq.${roomId}&executive_identity_id=eq.${resolved.context.actorId}`),
    client.request<JoinLink[]>("rpc/list_room_join_links",{method:"POST",body:JSON.stringify({target_room:roomId})}),
    client.request<boolean>("rpc/is_configured_founder",{method:"POST",body:"{}"}),
  ]);
  const room=roomResponse.data?.[0]; if(!room) notFound();
  const members=membersResponse.data??[]; const messages=messagesResponse.data??[];
  const names=new Map(members.map(member=>[member.executive_identity_id,member.display_name]));
  const ownDisplayName=session?await resolveExecutiveDisplayName(session).catch(()=>undefined):undefined;
  if(ownDisplayName)names.set(resolved.context.actorId,ownDisplayName);
  const myRole=members.find(member=>member.executive_identity_id===resolved.context.actorId)?.role;
  const pinned=new Set((pinsResponse.data??[]).map(pin=>pin.message_id)); const bookmarked=new Set((bookmarksResponse.data??[]).map(bookmark=>bookmark.message_id));
  const notice=(await searchParams).notice; const isFounder=founderResponse.data===true; const canModerate=myRole==="Owner"||myRole==="Moderator"; const canClear=myRole==="Owner"||(room.platform_managed&&isFounder);

  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-6 lg:px-10"><RoomPresenceHeartbeat roomId={room.id}/><div className="mb-5 flex items-center justify-between gap-4"><Link href="/rooms?directory=1" className="text-sm font-semibold text-[#526a86] hover:underline">← All Executive Rooms</Link><RoomLiveRefresh/></div>
    <PageHeader eyebrow={`${room.language_name} · ${room.permanence_status === "PendingFounderApproval" ? "Temporary — Founder review pending" : room.permanence_status} · ${room.platform_managed ? `${room.operator_label ?? "Atlas"} administered` : myRole ?? "Member"}`} title={room.title} description={room.short_purpose}/>
    <p className="mt-4 max-w-3xl text-sm leading-6 text-[#5f6b7a]">{room.topic}</p>
    <p className="mt-3 text-sm font-semibold text-[#526070]">{room.access_mode==="Open"?"Open to every verified executive":"Invitation only · visible to accepted members"}</p>
    {notice&&<p role="status" className="mt-6 rounded-xl border border-[#b9d9c3] bg-[#edf8f0] px-4 py-3 text-sm text-[#285a37]">{notice}</p>}
    {myRole==="Owner"&&room.access_mode==="InvitationOnly"&&<div className="mt-6"><RoomInviteLinkManager roomId={room.id} links={linksResponse.data??[]}/></div>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_19rem]">
      <section id="discussion"><div className="border-y border-[#dfe5ee] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 px-2 py-5 sm:px-5"><div><p className="atlas-kicker">Live channel</p><h2 className="mt-2 text-2xl font-semibold">#{room.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}</h2><p className="mt-2 text-sm text-[#63758b]">One continuous conversation. Messages appear automatically.</p></div><span className="text-xs font-semibold text-[#63758b]">{messages.length} messages</span></div>
        {messages.length ? <div className="border-t border-[#e5e9ed]">{messages.map(message=>{const author=message.message_kind==="Atlas"?"Atlas":names.get(message.author_identity_id)??"Verified executive";return <article key={message.id} className={`group flex gap-4 border-b border-[#edf0f3] px-2 py-6 sm:px-5 ${message.message_kind==="Atlas"?"bg-[#f7f9fc]":"bg-white"}`}><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-xs font-bold ${message.message_kind==="Atlas"?"bg-[#3457d5] text-white":"bg-[#e8edf3] text-[#344152]"}`}>{initials(author)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-3 gap-y-1"><span className="font-semibold text-[#182234]">{author}</span><time className="text-xs text-[#8a94a2]">{formatDate(message.created_at)}</time>{pinned.has(message.id)&&<span className="text-[11px] font-semibold text-[#77520e]">Pinned</span>}</div>{message.parent_message_id&&<p className="mt-1 text-xs font-semibold text-[#63758b]">Replying in this conversation</p>}{message.structured_context&&Object.keys(message.structured_context).length>0&&<p className="mt-2 text-xs font-semibold text-[#526070]">{[message.structured_context.serviceCategory,message.structured_context.city,message.structured_context.country].filter(Boolean).join(" · ")}</p>}<p className="mt-2 whitespace-pre-wrap text-[15px] leading-7 text-[#344152]">{message.body}</p>{message.message_kind==="Atlas"&&message.source_message_ids.length>0&&<p className="mt-2 text-xs text-[#63758b]">Sources preserved: {message.source_message_ids.length} room messages</p>}<div className="mt-2 flex gap-4 opacity-70 transition group-hover:opacity-100"><form action={toggleBookmarkAction}><input type="hidden" name="roomId" value={room.id}/><input type="hidden" name="messageId" value={message.id}/><button className="text-xs font-semibold text-[#526a86] hover:underline">{bookmarked.has(message.id)?"Remove bookmark":"Bookmark"}</button></form>{canModerate&&<form action={togglePinAction}><input type="hidden" name="roomId" value={room.id}/><input type="hidden" name="messageId" value={message.id}/><button className="text-xs font-semibold text-[#526a86] hover:underline">{pinned.has(message.id)?"Unpin":"Pin"}</button></form>}</div></div></article>})}</div>:<div className="border-t border-[#e5e9ed] px-5 py-16 text-center"><h3 className="text-lg font-semibold">Start the conversation</h3><p className="mt-2 text-sm text-[#5f6b7a]">Write the first message below. Everyone in the room will see it in this conversation.</p></div>}
        {room.status==="Active"&&<RoomEnterToSend><form action={postRoomMessageAction} className="sticky bottom-3 mt-6 rounded-2xl border border-[#cbd3dc] bg-white/95 p-4 shadow-lg backdrop-blur"><input type="hidden" name="roomId" value={room.id}/>{room.room_type==="ServiceMarketplace"&&<div className="mb-4 grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Service<input name="serviceCategory" required maxLength={80} className="mt-2 w-full rounded-xl border border-[#cbd3dc] px-3 py-2 font-normal" placeholder="Babysitting"/></label><label className="text-sm font-semibold">City<input name="serviceCity" required maxLength={100} className="mt-2 w-full rounded-xl border border-[#cbd3dc] px-3 py-2 font-normal" placeholder="Istanbul"/></label><label className="text-sm font-semibold">Country<input name="serviceCountry" required maxLength={100} className="mt-2 w-full rounded-xl border border-[#cbd3dc] px-3 py-2 font-normal" placeholder="Türkiye"/></label></div>}<label htmlFor="room-message" className="text-sm font-semibold">Message #{room.title}</label><div className="mt-2 flex items-end gap-2"><textarea id="room-message" name="body" required maxLength={4000} rows={2} className="min-h-12 flex-1 resize-y rounded-xl border border-[#9eb3ca] px-4 py-3 focus:border-[#3457d5] focus:outline-none focus:ring-2 focus:ring-[#3457d5]/20" placeholder={room.room_type==="ServiceMarketplace"?"Describe the service request or recommendation. Do not post sensitive personal details.":"Write a message to the channel…"}/><button className="rounded-xl bg-[#0b1220] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#1c2d45] active:translate-y-px">Send</button></div><p className="mt-2 text-xs text-[#63758b]">Enter to send · Shift+Enter for a new line</p>{!myRole&&room.access_mode==="Open"&&<p className="mt-1 text-xs text-[#63758b]">Sending your first message automatically joins this open room.</p>}</form></RoomEnterToSend>}
      </div></section>
      <aside className="space-y-5"><section className="rounded-2xl border border-[#a9c0d8] bg-[#f3f7fb] p-5"><p className="atlas-kicker">Atlas on request</p><h2 className="mt-2 text-xl font-semibold">Ask, then verify</h2><p className="mt-2 text-sm leading-6 text-[#526070]">Atlas is not monitoring this room. A request cites the room messages it uses and never trains on this discussion.</p>{room.status==="Active"&&<form action={invokeAtlasAction} className="mt-4"><input type="hidden" name="roomId" value={room.id}/><label className="sr-only" htmlFor="atlas-request">Atlas request</label><textarea id="atlas-request" name="request" required minLength={3} maxLength={500} rows={3} className="w-full rounded-xl border border-[#b9c8d8] bg-white px-3 py-2 text-sm" placeholder="Summarize the decision and unresolved questions."/><button className="mt-3 w-full rounded-full bg-[#244b73] px-4 py-2.5 text-sm font-semibold text-white">Ask Atlas explicitly</button></form>}</section>
        <section className="rounded-2xl border border-[#dfe5ee] bg-white p-5"><p className="atlas-kicker">Members</p><h2 className="mt-2 text-xl font-semibold">{members.length} verified {members.length===1?"executive":"executives"}</h2><ul className="mt-4 space-y-3">{members.map(member=><li key={member.executive_identity_id} className="flex items-center justify-between gap-3 text-sm"><span>{names.get(member.executive_identity_id)??"Verified executive"}</span><span className="text-xs font-semibold text-[#63758b]">{member.role}</span></li>)}</ul>{myRole==="Owner"&&room.status==="Active"&&<form action={inviteMemberAction} className="mt-5 border-t border-[#e5e9ed] pt-5"><input type="hidden" name="roomId" value={room.id}/><label className="text-sm font-semibold">Invite a verified executive<input name="email" type="email" required className="mt-2 w-full rounded-xl border border-[#cbd3dc] px-3 py-2 font-normal" placeholder="name@company.com"/></label><select name="role" className="mt-3 w-full rounded-xl border border-[#cbd3dc] px-3 py-2 text-sm"><option>Participant</option><option>Moderator</option></select><button className="mt-3 w-full rounded-full border border-[#9eb3ca] px-4 py-2 text-sm font-semibold">Send private invitation</button></form>}</section>
        <section className="rounded-2xl border border-[#dfe5ee] bg-white p-5 text-sm text-[#5f6b7a]"><p><strong className="text-[#0b1220]">Access:</strong> {room.access_mode==="Open"?"open to signed-in, verified ORENDALIS executives.":"invitation only; members join through a secure link or direct invitation."}</p><p className="mt-2"><strong className="text-[#0b1220]">Language:</strong> {room.language_name}.</p><p className="mt-2"><strong className="text-[#0b1220]">Retention:</strong> 90-day bounded archive window.</p>{room.is_temporary&&<p className="mt-2"><strong className="text-[#0b1220]">Temporary until:</strong> {formatDate(room.closes_at)} or the Founder&apos;s permanence decision.</p>}{canClear&&messages.length>0&&<form action={clearRoomConversationAction} className="mt-5 border-t border-[#ead7d4] pt-4"><input type="hidden" name="roomId" value={room.id}/><label className="flex items-start gap-2 text-xs leading-5"><input type="checkbox" name="confirmClear" value="yes" required className="mt-1"/>I understand this clears the visible conversation for everyone while retaining a governance record.</label><button className="mt-3 text-sm font-semibold text-[#8b3c34] underline-offset-4 hover:underline">Clear all chat</button></form>}{myRole==="Owner"&&room.status==="Active"&&<form action={archiveRoomAction} className="mt-4"><input type="hidden" name="roomId" value={room.id}/><button className="text-sm font-semibold text-[#8b3c34] underline-offset-4 hover:underline">Archive this room</button></form>}</section>
      </aside>
    </div>
  </main>;
}
function formatDate(value?:string){if(!value)return"Not set";const date=new Date(value);return Number.isNaN(date.getTime())?"Not set":new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(date);}
function initials(value:string){return value.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"E";}
