import type { Repository, RepositoryCapabilities, RepositoryContext, RepositoryHealth, RepositoryMetadata, RepositoryQuery, RepositoryResult } from "@/lib/repositories/types";
import type { SupabaseDataClient } from "@/lib/supabase/client";
import { mapSupabaseError } from "@/lib/supabase/errors";
import type { SupabaseRow } from "@/lib/supabase/types";
import type { SupabaseMapper } from "./mapper";

export { jsonPayloadMapper } from "./mapper";

const capabilities: RepositoryCapabilities = { read: true, write: true, append: true, archive: true, transactions: false, search: true, optimisticConcurrency: true, migrations: true };
export class SupabaseRepository<T extends { id: string }> implements Repository<T> {
  readonly capabilities = capabilities;
  constructor(readonly name: string, readonly table: string, protected client: SupabaseDataClient, protected mapper: SupabaseMapper<T>, protected appendOnly = false) {}
  private metadata(recordCount?: number): RepositoryMetadata { return { provider: "Supabase", repository: this.name, version: "1.0.0", durationMs: 0, recordCount }; }
  private failure<V>(error: { message: string; code?: string }, status: number): RepositoryResult<V> { return { ok: false, error: mapSupabaseError(error, status), metadata: this.metadata() }; }
  private workspace(context?: RepositoryContext) { if (!context?.workspace) throw new Error(`${this.name} requires WorkspaceContext`); return context.workspace.workspaceId; }
  async findById(id: string, context?: RepositoryContext) { const workspace = this.workspace(context); const response = await this.client.request<SupabaseRow[]>(`${this.table}?domain_id=eq.${encodeURIComponent(id)}&workspace_id=eq.${workspace}&limit=1`); if (response.error) return this.failure<T | undefined>(response.error, response.status); return { ok: true as const, value: response.data?.[0] ? this.mapper.toDomain(response.data[0]) : undefined, metadata: this.metadata(response.data?.length ?? 0) }; }
  async findMany(query?: RepositoryQuery<T>, context?: RepositoryContext) { const workspace = this.workspace(context); const parameters = [`workspace_id=eq.${workspace}`]; for (const filter of query?.filters ?? []) if (filter.operator === "equals") parameters.push(`${String(filter.field)}=eq.${encodeURIComponent(String(filter.value))}`); for (const sort of query?.sort ?? []) parameters.push(`order=${String(sort.field)}.${sort.direction}`); if (query?.pagination) parameters.push(`offset=${query.pagination.offset}`, `limit=${query.pagination.limit}`); const response = await this.client.request<SupabaseRow[]>(`${this.table}?${parameters.join("&")}`); if (response.error) return this.failure<readonly T[]>(response.error, response.status); const values = (response.data ?? []).map((row) => this.mapper.toDomain(row)); return { ok: true as const, value: values, metadata: this.metadata(values.length) }; }
  async create(entity: T, context?: RepositoryContext) { this.workspace(context); const response = await this.client.request<SupabaseRow[]>(this.table, { method: "POST", body: JSON.stringify(this.mapper.toInsert(entity, context!)) }); if (response.error) return this.failure<T>(response.error, response.status); return { ok: true as const, value: response.data?.[0] ? this.mapper.toDomain(response.data[0]) : entity, metadata: this.metadata(1) }; }
  async update(id: string, changes: Partial<Omit<T, "id">>, context?: RepositoryContext) { if (this.appendOnly) return this.failure<T>({ message: `${this.name} is append-only` }, 409); const workspace = this.workspace(context); const response = await this.client.request<SupabaseRow[]>(`${this.table}?domain_id=eq.${encodeURIComponent(id)}&workspace_id=eq.${workspace}`, { method: "PATCH", body: JSON.stringify(this.mapper.toUpdate(changes as Partial<T>)) }); if (response.error) return this.failure<T>(response.error, response.status); if (!response.data?.[0]) return this.failure<T>({ message: `${id} was not found` }, 404); return { ok: true as const, value: this.mapper.toDomain(response.data[0]), metadata: this.metadata(1) }; }
  private async setArchived(id: string, archivedAt: string | null, context?: RepositoryContext) { if (this.appendOnly) return this.failure<T>({ message: `${this.name} is append-only; append an event instead` }, 409); const workspace = this.workspace(context); const response = await this.client.request<SupabaseRow[]>(`${this.table}?domain_id=eq.${encodeURIComponent(id)}&workspace_id=eq.${workspace}`, { method: "PATCH", body: JSON.stringify({ archived_at: archivedAt, updated_at: new Date().toISOString() }) }); if (response.error) return this.failure<T>(response.error, response.status); if (!response.data?.[0]) return this.failure<T>({ message: `${id} was not found` }, 404); return { ok: true as const, value: this.mapper.toDomain(response.data[0]), metadata: this.metadata(1) }; }
  archive(id: string, context?: RepositoryContext) { return this.setArchived(id, new Date().toISOString(), context); }
  restore(id: string, context?: RepositoryContext) { return this.setArchived(id, null, context); }
  append(entity: T, context?: RepositoryContext) { return this.create(entity, context); }
  async exists(id: string, context?: RepositoryContext) { const result = await this.findById(id, context); return result.ok ? { ok: true as const, value: result.value !== undefined, metadata: result.metadata } : result; }
  async count(query?: RepositoryQuery<T>, context?: RepositoryContext) { const result = await this.findMany(query, context); return result.ok ? { ok: true as const, value: result.value.length, metadata: result.metadata } : result; }
  async search(term: string, context?: RepositoryContext) { const workspace = this.workspace(context); const response = await this.client.request<SupabaseRow[]>(`${this.table}?workspace_id=eq.${workspace}&payload=cs.${encodeURIComponent(JSON.stringify({ search: term }))}`); if (response.error) return this.failure<readonly T[]>(response.error, response.status); const values = (response.data ?? []).map((row) => this.mapper.toDomain(row)); return { ok: true as const, value: values, metadata: this.metadata(values.length) }; }
  validate(entity: T) { return { ok: true as const, value: entity.id.trim() ? [] : ["ID_REQUIRED"], metadata: this.metadata() }; }
  async health(): Promise<RepositoryHealth> { return { status: await this.client.health() ? "healthy" : "unavailable", checkedAt: new Date().toISOString(), provider: "Supabase", message: "Supabase PostgREST repository health." }; }
}
