export type RepositoryOperation<T>=T|Promise<T>;export type RepositoryProviderKind="Memory"|"Local Storage"|"IndexedDB"|"Supabase"|"PostgreSQL"|"REST"|"GraphQL"|"Enterprise";
export interface RepositoryContext{requestId:string;actorId:string;correlationId:string;timestamp:string;transactionId?:string;workspace?:import("@/lib/workspaces").WorkspaceContext}
export interface RepositoryMetadata{provider:RepositoryProviderKind;repository:string;version:string;durationMs:number;recordCount?:number;fromCache?:boolean}
export interface RepositoryError{code:"NOT_FOUND"|"VALIDATION"|"CONFLICT"|"CONCURRENCY"|"PROVIDER"|"READ_ONLY"|"APPEND_ONLY";message:string;retryable:boolean;details?:Readonly<Record<string,string|number|boolean>>}
export type RepositoryResult<T>={ok:true;value:T;metadata:RepositoryMetadata}|{ok:false;error:RepositoryError;metadata:RepositoryMetadata};
export interface RepositoryFilter<T>{field:keyof T;operator:"equals"|"not-equals"|"contains"|"in"|"before"|"after";value:unknown}
export interface RepositorySort<T>{field:keyof T;direction:"asc"|"desc"}
export interface RepositoryPagination{offset:number;limit:number}
export interface RepositoryQuery<T>{filters?:readonly RepositoryFilter<T>[];sort?:readonly RepositorySort<T>[];pagination?:RepositoryPagination;search?:string}
export interface RepositoryCapabilities{read:boolean;write:boolean;append:boolean;archive:boolean;transactions:boolean;search:boolean;optimisticConcurrency:boolean;migrations:boolean}
export interface RepositoryHealth{status:"healthy"|"degraded"|"unavailable";checkedAt:string;provider:RepositoryProviderKind;message:string;latencyMs?:number}
export interface RepositoryAudit{id:string;repository:string;operation:string;entityId?:string;actorId:string;occurredAt:string;correlationId:string;changes?:Readonly<Record<string,unknown>>}
export interface RepositoryEvent<T>{id:string;type:"created"|"updated"|"appended"|"archived"|"restored";entity:T;occurredAt:string;context:RepositoryContext}
export interface RepositoryMigration{id:string;fromVersion:string;toVersion:string;description:string;apply(provider:RepositoryProvider):RepositoryOperation<RepositoryResult<void>>}
export interface RepositoryProvider{id:string;kind:RepositoryProviderKind;version:string;capabilities:RepositoryCapabilities;connect():RepositoryOperation<RepositoryResult<void>>;disconnect():RepositoryOperation<RepositoryResult<void>>;health():RepositoryOperation<RepositoryHealth>;migrations():RepositoryOperation<readonly RepositoryMigration[]>}
export interface RepositoryTransaction{id:string;state:"active"|"committed"|"rolled-back";commit():RepositoryOperation<RepositoryResult<void>>;rollback():RepositoryOperation<RepositoryResult<void>>}
export interface Repository<T extends {id:string}>{readonly name:string;readonly capabilities:RepositoryCapabilities;findById(id:string,context?:RepositoryContext):RepositoryOperation<RepositoryResult<T|undefined>>;findMany(query?:RepositoryQuery<T>,context?:RepositoryContext):RepositoryOperation<RepositoryResult<readonly T[]>>;create(entity:T,context?:RepositoryContext):RepositoryOperation<RepositoryResult<T>>;update(id:string,changes:Partial<Omit<T,"id">>,context?:RepositoryContext):RepositoryOperation<RepositoryResult<T>>;archive(id:string,context?:RepositoryContext):RepositoryOperation<RepositoryResult<T>>;restore(id:string,context?:RepositoryContext):RepositoryOperation<RepositoryResult<T>>;append(entity:T,context?:RepositoryContext):RepositoryOperation<RepositoryResult<T>>;exists(id:string,context?:RepositoryContext):RepositoryOperation<RepositoryResult<boolean>>;count(query?:RepositoryQuery<T>,context?:RepositoryContext):RepositoryOperation<RepositoryResult<number>>;search(term:string,context?:RepositoryContext):RepositoryOperation<RepositoryResult<readonly T[]>>;validate(entity:T,context?:RepositoryContext):RepositoryOperation<RepositoryResult<readonly string[]>>;health():RepositoryOperation<RepositoryHealth>}
