"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { ManagedInvitation } from "@/lib/beta/invitation-management";
import { PrimaryButton } from "@/components/primary-button";
import { SecondaryButton } from "@/components/secondary-button";
import { SectionCard } from "@/components/section-card";
import { StatusBadge } from "@/components/status-badge";

const field="mt-2 w-full rounded-xl border border-[#cbd5e1] bg-white px-4 py-3 text-[#182234] outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20";
const statusTone={Pending:"info",Accepted:"success",Expired:"warning",Revoked:"neutral"} as const;
function format(value?:string){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";}

export function InvitationManagement({initialInvitations}:{initialInvitations:ManagedInvitation[]}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [link,setLink]=useState("");const [copied,setCopied]=useState(false);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setError("");setLink("");const data=new FormData(form);const response=await fetch("/api/company-control/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),expiresAt:new Date(String(data.get("expiresAt"))).toISOString()})});const body=await response.json() as {error?:string;invitationLink?:string};setBusy(false);if(!response.ok){setError(body.error??"Invitation was not created.");return;}setLink(body.invitationLink??"");form.reset();router.refresh();}
  async function revoke(id:string){if(!window.confirm("Revoke this invitation? Its link will stop working immediately."))return;setBusy(true);setError("");const response=await fetch("/api/company-control/invitations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const body=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(body.error??"Invitation was not revoked.");return;}router.refresh();}
  async function copy(){await navigator.clipboard.writeText(link);setCopied(true);window.setTimeout(()=>setCopied(false),2000);}
  return <div className="space-y-6">
    <SectionCard><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><div><p className="atlas-kicker">New executive access</p><h2 className="mt-2 text-xl font-semibold text-[#182234]">Create invitation</h2><p className="mt-2 text-sm text-[#657184]">Invitations are single-use, email-bound and expire automatically.</p><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={create}><label className="text-sm text-[#354052] sm:col-span-2">Invited email<input name="email" type="email" required autoComplete="off" placeholder="executive@example.com" className={field}/></label><label className="text-sm text-[#354052]">Expires<input name="expiresAt" type="datetime-local" required className={field}/></label><div className="flex items-end"><PrimaryButton type="submit" disabled={busy}>{busy?"Creating…":"Create invitation"}</PrimaryButton></div></form>{error&&<p className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700" role="alert">{error}</p>}</div><div className="rounded-xl border border-[#dce3ec] bg-[#f8fafc] p-5"><h3 className="font-medium text-[#182234]">Secure delivery</h3>{link?<><p className="mt-2 text-sm text-[#657184]">Copy this link now. The secure token is not stored in recoverable form.</p><label className="mt-4 block text-xs text-[#657184]">Invitation link<input readOnly value={link} className={`${field} font-mono text-xs`}/></label><SecondaryButton className="mt-3" onClick={copy}>{copied?"Copied":"Copy invitation link"}</SecondaryButton></>:<p className="mt-3 text-sm text-[#657184]">The one-time access link appears here after creation.</p>}</div></div></SectionCard>
    <SectionCard><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="atlas-kicker">Access register</p><h2 className="mt-2 text-xl font-semibold text-[#182234]">Executive invitations</h2></div><p className="text-sm text-[#657184]">{initialInvitations.length} total</p></div>{initialInvitations.length?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><caption className="sr-only">Founder-managed executive invitations</caption><thead className="border-b border-[#dce3ec] text-xs uppercase tracking-wider text-[#657184]"><tr>{["Invited email","Status","Created","Expires","Accepted","Creator","Action"].map(item=><th key={item} scope="col" className="px-3 py-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-[#edf1f5]">{initialInvitations.map(item=><tr key={item.id}><th scope="row" className="px-3 py-4 font-medium text-[#182234]">{item.email}</th><td className="px-3 py-4"><StatusBadge tone={statusTone[item.status]}>{item.status}</StatusBadge></td><td className="px-3 py-4 text-[#657184]">{format(item.createdAt)}</td><td className="px-3 py-4 text-[#657184]">{format(item.expiresAt)}</td><td className="px-3 py-4 text-[#657184]">{format(item.acceptedAt)}</td><td className="px-3 py-4 text-[#657184]">{item.createdBy}</td><td className="px-3 py-4">{item.status==="Pending"?<SecondaryButton disabled={busy} onClick={()=>revoke(item.id)}>Revoke</SecondaryButton>:<span className="text-xs text-[#7a8798]">Complete</span>}</td></tr>)}</tbody></table></div>:<div className="mt-5 rounded-xl border border-dashed border-[#cbd5e1] p-8 text-center"><p className="font-medium text-[#182234]">No invitations yet</p><p className="mt-2 text-sm text-[#657184]">Create an executive invitation when access is approved.</p></div>}</SectionCard>
  </div>;
}
