"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { ManagedInvitation } from "@/lib/beta/invitation-management";
import { PrimaryButton } from "@/components/primary-button";
import { SecondaryButton } from "@/components/secondary-button";
import { SectionCard } from "@/components/section-card";
import { StatusBadge } from "@/components/status-badge";

const field="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-400/30";
const statusTone={Pending:"info",Accepted:"success",Expired:"warning",Revoked:"neutral"} as const;
function format(value?:string){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";}

export function InvitationManagement({initialInvitations}:{initialInvitations:ManagedInvitation[]}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [link,setLink]=useState("");const [copied,setCopied]=useState(false);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setError("");setLink("");const data=new FormData(form);const response=await fetch("/api/company-control/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),expiresAt:new Date(String(data.get("expiresAt"))).toISOString()})});const body=await response.json() as {error?:string;invitationLink?:string};setBusy(false);if(!response.ok){setError(body.error??"Invitation was not created.");return;}setLink(body.invitationLink??"");form.reset();router.refresh();}
  async function revoke(id:string){if(!window.confirm("Revoke this invitation? Its link will stop working immediately."))return;setBusy(true);setError("");const response=await fetch("/api/company-control/invitations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const body=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(body.error??"Invitation was not revoked.");return;}router.refresh();}
  async function copy(){await navigator.clipboard.writeText(link);setCopied(true);window.setTimeout(()=>setCopied(false),2000);}
  return <div className="space-y-6">
    <aside className="rounded-2xl border border-amber-300/20 bg-amber-300/[.07] p-4" aria-label="Development delivery mode"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-amber-100">Development Mode</p><p className="mt-1 text-sm text-amber-100/70">Email delivery is not connected. New invitation links are shown once for secure copying.</p></div><StatusBadge tone="warning">Manual delivery</StatusBadge></div></aside>
    <SectionCard><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><div><p className="atlas-kicker">New executive access</p><h2 className="mt-2 text-xl font-semibold">Create Invitation</h2><p className="mt-2 text-sm text-slate-400">Invitations are single-use, email-bound, and expire automatically.</p><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={create}><label className="text-sm text-slate-300 sm:col-span-2">Invited email<input name="email" type="email" required autoComplete="off" placeholder="executive@example.com" className={field}/></label><label className="text-sm text-slate-300">Expires<input name="expiresAt" type="datetime-local" required className={field}/></label><div className="flex items-end"><PrimaryButton type="submit" disabled={busy}>{busy?"Creating…":"Create Invitation"}</PrimaryButton></div></form>{error&&<p className="mt-4 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200" role="alert">{error}</p>}</div><div className="rounded-xl border border-white/10 bg-slate-950/40 p-5"><h3 className="font-medium">Delivery</h3>{link?<><p className="mt-2 text-sm text-slate-400">Copy this link now. The secure token is not stored in recoverable form.</p><label className="mt-4 block text-xs text-slate-500">Invitation link<input readOnly value={link} className={`${field} font-mono text-xs`}/></label><SecondaryButton className="mt-3" onClick={copy}>{copied?"Copied":"Copy Invitation Link"}</SecondaryButton></>:<p className="mt-3 text-sm text-slate-500">The one-time link will appear here after creation.</p>}<div className="mt-5 border-t border-white/10 pt-4"><p className="text-sm font-medium text-slate-300">Email resend</p><p className="mt-1 text-xs text-slate-500">Available when a verified email delivery provider is connected.</p><SecondaryButton className="mt-3" disabled>Resend Unavailable</SecondaryButton></div></div></div></SectionCard>
    <SectionCard><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="atlas-kicker">Invitation register</p><h2 className="mt-2 text-xl font-semibold">Beta Invitations</h2></div><p className="text-sm text-slate-500">{initialInvitations.length} total</p></div>{initialInvitations.length?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><caption className="sr-only">Founder-managed beta invitations</caption><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><tr>{["Invited email","Status","Created","Expires","Accepted","Creator","Action"].map(item=><th key={item} scope="col" className="px-3 py-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-white/5">{initialInvitations.map(item=><tr key={item.id}><th scope="row" className="px-3 py-4 font-medium text-white">{item.email}</th><td className="px-3 py-4"><StatusBadge tone={statusTone[item.status]}>{item.status}</StatusBadge></td><td className="px-3 py-4 text-slate-400">{format(item.createdAt)}</td><td className="px-3 py-4 text-slate-400">{format(item.expiresAt)}</td><td className="px-3 py-4 text-slate-400">{format(item.acceptedAt)}</td><td className="px-3 py-4 text-slate-400">{item.createdBy}</td><td className="px-3 py-4">{item.status==="Pending"?<SecondaryButton disabled={busy} onClick={()=>revoke(item.id)}>Revoke</SecondaryButton>:<span className="text-xs text-slate-600">No action</span>}</td></tr>)}</tbody></table></div>:<div className="mt-5 rounded-xl border border-dashed border-white/10 p-8 text-center"><p className="font-medium">No Invitations Yet</p><p className="mt-2 text-sm text-slate-500">Create the first private beta invitation above.</p></div>}</SectionCard>
  </div>;
}
