import type { SerializableValue } from "./career-ledger";
export type BlueprintPriority="critical"|"high"|"medium"|"low"; export type BlueprintSectionStatus="empty"|"partial"|"confirmed"|"stale"; export type BlueprintCompletenessState="Not Started"|"Basic"|"Developing"|"Strong"|"Decision Ready";
export interface BlueprintEvidence{id:string;label:string;source:"Executive"|"Document"|"Career Ledger"|"Demonstration";reference?:string;recordedAt:string;confidence:number;isDemo:true}
export interface StructuredPreference{id:string;category:string;value:string;priority:BlueprintPriority;weight:number;requirement:"required"|"preferred";direction:"positive"|"exclusion";confidence:number;evidenceIds:readonly string[];source:string;validFrom:string;validUntil?:string;lastConfirmedAt:string;revisionId:string;notes:string;isDemo:true}
export interface ExecutiveIdentity{name:string;headline:string;currentRole:string;languages:readonly string[];executiveBrand:string}
export interface CareerVision{statement:string;threeYearObjective:string;fiveYearObjective:string;tenYearObjective:string;horizon:"3 years"|"5 years"|"10 years"|"Long term"}
export interface CareerObjective{id:string;title:string;description:string;horizon:string;priority:BlueprintPriority;boardExposure:boolean}
export interface ExecutiveDNA{id:string;dimension:string;leftLabel:string;rightLabel:string;position:number;evidenceIds:readonly string[]}
export interface LeadershipProfile{style:string;scope:string;targetTeamSize:string;targetPL:string;strengths:readonly string[];developmentAreas:readonly string[]}
export interface ExecutivePrinciple{id:string;title:string;ruleType:"compensation"|"travel"|"relocation"|"leadership"|"industry"|"ethics"|"work-life";operator:"minimum"|"maximum"|"exclude"|"require";value:string;explanation:string;isNonNegotiable:true}
export type IndustryPreference=StructuredPreference; export type GeographicPreference=StructuredPreference; export type CompanyPreference=StructuredPreference; export type RolePreference=StructuredPreference; export type WorkArrangementPreference=StructuredPreference; export type OwnershipPreference=StructuredPreference; export type CulturePreference=StructuredPreference;
export interface TravelPreference{maximumPercent:number;international:boolean;notes:string} export interface CompensationPreference{target:number;minimum:number;currency:string;baseWeight:number;bonusWeight:number;equityWeight:number;benefitsWeight:number}
export interface CareerConstraint{id:string;category:string;description:string;severity:"non-negotiable"|"important";principleId?:string} export type LifestyleConstraint=CareerConstraint; export type FamilyConstraint=CareerConstraint;
export interface RiskProfile{tolerance:"low"|"moderate"|"high";startupTolerance:"low"|"moderate"|"high";description:string} export interface NegotiationProfile{style:string;preferredSequence:readonly string[];walkAwayClarity:string} export interface DecisionStyle{style:string;timeHorizon:string;evidenceThreshold:string}
export interface BoardAspiration{target:string;timeframe:string;advisoryInterest:boolean;exposureObjectiveId?:string} export interface LearningGoal{id:string;topic:string;targetDate:string;priority:BlueprintPriority} export type CareerHorizon=CareerVision["horizon"];
export interface BlueprintRevision{id:string;revisionNumber:number;createdAt:string;effectiveAt:string;changedBy:"Executive"|"Atlas"|"System";changeReason:string;changedFields:readonly string[];previousValues:Readonly<Record<string,SerializableValue>>;newValues:Readonly<Record<string,SerializableValue>>;evidenceIds:readonly string[];confidence:number;status:"Draft"|"Approved"|"Rejected";ledgerEntryId?:string;isDemo:true}
export interface BlueprintConflict{id:string;type:string;severity:"warning"|"critical";title:string;explanation:string;fields:readonly string[];principleId?:string;resolution:"unresolved";isDemo:true}
export interface BlueprintSectionAssessment{section:string;status:BlueprintSectionStatus;requiredFields:number;completedFields:number;confirmedAt?:string;evidenceCount:number}
export interface BlueprintCompleteness{state:BlueprintCompletenessState;score:number;sections:readonly BlueprintSectionAssessment[];factors:readonly string[];missingRequired:readonly string[];staleSections:readonly string[];conflictCount:number;assessedAt:string}
export interface DecisionPriority{id:string;factor:string;rank:number;weight:number}
export interface ExecutiveBlueprint{id:string;revisionId:string;revisionNumber:number;identity:ExecutiveIdentity;currentPositioning:string;vision:CareerVision;objectives:readonly CareerObjective[];dna:readonly ExecutiveDNA[];leadership:LeadershipProfile;preferences:readonly StructuredPreference[];travel:TravelPreference;compensation:CompensationPreference;principles:readonly ExecutivePrinciple[];constraints:readonly CareerConstraint[];risk:RiskProfile;negotiation:NegotiationProfile;decisionStyle:DecisionStyle;board:BoardAspiration;learningGoals:readonly LearningGoal[];decisionPriorities:readonly DecisionPriority[];purposeAndValues:readonly string[];retirementHorizon:string;evidence:readonly BlueprintEvidence[];revisions:readonly BlueprintRevision[];lastConfirmedAt:string;nextReviewAt:string;sectionStatus:Readonly<Record<string,BlueprintSectionStatus>>;isDemo:true}
export interface BlueprintAlignment{score:number;summary:string;matched:readonly string[];violated:readonly string[];nonNegotiableConflicts:readonly string[];missingInformation:readonly string[];revisionId:string}
