"use client";

import { useState } from "react";

interface Draft {id:string;organizationName:string;roleTitle:string;startDate?:string;endDate?:string;isCurrent:boolean;confidence:"High"|"Medium"|"Low";evidence:string}
interface Result {filename:string;format:string;text:string;drafts:Draft[];warnings:string[];error?:string}

export function HistoryFileImport({saveAction}:{saveAction:(form:FormData)=>Promise<void>}){
  const[result,setResult]=useState<Result>(),[error,setError]=useState<string>(),[loading,setLoading]=useState(false),[consent,setConsent]=useState(false);
  async function choose(file?:File){if(!file)return;setLoading(true);setError(undefined);setResult(undefined);try{const body=new FormData();body.set("file",file);const response=await fetch("/api/import/extract",{method:"POST",body});const next=await response.json() as Result;if(!response.ok)throw new Error(next.error??"The document could not be extracted.");setResult(next);}catch(reason){setError(reason instanceof Error?reason.message:"The document could not be extracted.");}finally{setLoading(false);}}
  return <section className="mt-5 rounded-2xl border border-blue-400/20 bg-blue-400/[.04] p-5">
    <p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-300">Import a CV or resume</p>
    <h3 className="mt-2 text-lg font-semibold">Create an editable review draft</h3>
    <p className="mt-2 text-sm leading-6 text-slate-400">Supported: PDF, DOCX, TXT, Markdown, CSV, and JSON up to 5 MB. Legacy DOC files must be saved as DOCX or PDF. The raw file is not retained.</p>
    <label className="mt-4 flex items-start gap-3 text-sm text-slate-300"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)} className="mt-1 accent-blue-500"/><span>I consent to local text extraction for review. Nothing enters Career Memory until I confirm it.</span></label>
    <label className={`mt-4 block rounded-xl border border-dashed p-5 text-center ${consent?"cursor-pointer border-white/20":"cursor-not-allowed border-white/10 opacity-50"}`}><span className="text-sm font-medium">{loading?"Extracting safely…":"Choose CV or resume"}</span><input className="sr-only" type="file" accept=".pdf,.docx,.txt,.md,.csv,.json" disabled={!consent||loading} onChange={event=>choose(event.target.files?.[0])}/></label>
    {error&&<p role="alert" className="mt-4 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}
    {result&&<div className="mt-5 space-y-4"><div className="flex flex-wrap items-center justify-between gap-2 text-sm"><p className="font-medium text-white">{result.filename}</p><p className="text-slate-500">{result.format} · raw file discarded after extraction</p></div>{result.warnings.map(warning=><p key={warning} className="rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-3 text-sm text-amber-100">{warning}</p>)}
      {result.drafts.length>0&&<form action={saveAction} className="space-y-4"><input type="hidden" name="sourceFilename" value={result.filename}/>{result.drafts.map((draft,index)=><fieldset key={draft.id} className="rounded-xl border border-white/10 bg-slate-950/60 p-4"><legend className="px-2 text-sm font-semibold text-white">Role {index+1} · {draft.confidence} extraction confidence</legend><div className="mt-2 grid gap-3 sm:grid-cols-2"><Field label="Organization" name="organizationName" value={draft.organizationName}/><Field label="Executive role" name="roleTitle" value={draft.roleTitle}/><Field label="Start date" name="startDate" value={draft.startDate??""} type="month" required={false}/><Field label="End date" name="endDate" value={draft.endDate??""} type="month" required={false}/><label className="text-sm text-slate-300">Current role<select name="isCurrent" defaultValue={String(draft.isCurrent)} className="mt-2 w-full rounded-lg border border-white/10 bg-slate-950 p-3"><option value="true">Yes</option><option value="false">No</option></select></label><label className="text-sm text-slate-300">Review decision<select name="decision" defaultValue="Accept" className="mt-2 w-full rounded-lg border border-white/10 bg-slate-950 p-3"><option>Accept</option><option>Edit</option><option>Reject</option><option>Uncertain</option></select></label></div><p className="mt-3 text-xs leading-5 text-slate-500">Source evidence: {draft.evidence}</p></fieldset>)}<button className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950">Confirm accepted history records</button></form>}
      <details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer text-sm font-medium text-slate-300">Review extracted text</summary><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs leading-5 text-slate-500">{result.text}</pre></details>
    </div>}
  </section>;
}

function Field({label,name,value,type="text",required=true}:{label:string;name:string;value:string;type?:string;required?:boolean}){return <label className="text-sm text-slate-300">{label}<input name={name} type={type} defaultValue={value} required={required} className="mt-2 w-full rounded-lg border border-white/10 bg-slate-950 p-3 text-white"/></label>}
