import Link from "next/link";
import type { Locale } from "@/lib/locale";
import { RoomsStatusLink } from "@/components/rooms/rooms-status-link";

export function ExecutiveCommandBar({ focusMode, onToggleFocus, locale = "en", signedInName, signedInEmail }: { focusMode: boolean; onToggleFocus: () => void; locale?: Locale; signedInName?: string; signedInEmail?: string }) {
  const tr = locale === "tr";
  const identityLabel = signedInName ?? signedInEmail;
  return <header className="sticky top-0 z-20 hidden h-16 items-center justify-between border-b border-[#e5e7e8] bg-white/90 px-8 backdrop-blur-xl lg:flex"><div className="flex items-center gap-3"><Link href="/assistant" className="flex items-center gap-3 rounded-lg px-2 py-1 hover:bg-[#f3f6fb] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3457d5]" aria-label="Open Atlas"><span className="size-2 rounded-full bg-emerald-500"/><div><p className="text-xs font-medium text-[#30343a]">{tr ? "Atlas hazır" : "Atlas is ready"}</p><p className="text-[11px] text-[#7a8086]">{identityLabel ?? (tr ? "İkinci bir bakış istediğinde yanında" : "Ask when you want a second perspective")}</p></div></Link>{identityLabel&&<RoomsStatusLink/>}</div><nav className="flex items-center gap-1" aria-label="Executive shortcuts"><Link href="/opportunities" className="rounded-lg px-3 py-2 text-sm text-[#687078] hover:bg-[#f3f4f4] hover:text-[#17191c]">{tr ? "İş ara" : "Search jobs"}</Link><Link href="/applications" className="rounded-lg px-3 py-2 text-sm text-[#687078] hover:bg-[#f3f4f4] hover:text-[#17191c]">{tr ? "Başvurular" : "Applications"}</Link><Link href="/workspace" className="rounded-lg px-3 py-2 text-sm text-[#687078] hover:bg-[#f3f4f4] hover:text-[#17191c]">{tr ? "Profil" : "Profile"}</Link><Link href="/invite" className="rounded-lg px-3 py-2 text-sm text-[#687078] hover:bg-[#f3f4f4] hover:text-[#17191c]">Invite</Link><button type="button" onClick={onToggleFocus} aria-pressed={focusMode} className={`ml-2 rounded-full border px-3 py-2 text-sm transition ${focusMode ? "border-[#7894a6] bg-[#eef3f5] text-[#36576a]" : "border-[#d9dcde] text-[#687078] hover:text-[#17191c]"}`}>{focusMode ? (tr ? "Menüyü göster" : "Show navigation") : (tr ? "Odaklan" : "Focus")}</button></nav></header>;
}
