import type { ExecutiveGeographicProfile } from "@/lib/opportunity-geography";

export function ExecutivePreferencesForm({ profile, action, saved }: { profile: ExecutiveGeographicProfile; action: (formData: FormData) => void | Promise<void>; saved?: boolean }) {
  const p = profile.manualPreferences, join = (values: string[]) => values.join(", ");
  return <section id="preferences" className="mt-8 rounded-2xl border border-[#e3e5e6] bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#936b3f]">Executive control</p><h2 className="mt-2 text-2xl font-semibold">Opportunity preferences</h2><p className="mt-2 text-sm leading-6 text-[#626970]">Your choices are stored as <strong>User Preferences</strong>. Atlas recommendations and automatically detected information remain separate and never replace them.</p>{saved && <p role="status" className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Your preferences were saved and will influence future rankings.</p>}<div className="mt-5 grid gap-4 md:grid-cols-2"><Source label="User Preference" value={p.updatedAt ? `Last updated ${new Date(p.updatedAt).toLocaleDateString("en-GB")}` : "Not set"}/><Source label="Detected Information" value={[profile.currentCountry.value, ...profile.workAuthorizations.value].filter(Boolean).join(", ") || "Nothing confirmed"}/></div><form action={action} className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Preferred locations" name="locations" value={join(p.locations)}/><Field label="Preferred countries" name="countries" value={join(p.countries)}/><Field label="Preferred industries" name="industries" value={join(p.industries)}/><Field label="Preferred titles" name="titles" value={join(p.titles)}/><Field label="Preferred seniority" name="seniorities" value={join(p.seniorities)}/><Field label="Employment types" name="employmentTypes" value={join(p.employmentTypes)}/><Field label="Remote preferences" name="remotePreferences" value={join(p.remotePreferences)}/><Field label="Company sizes" name="companySizes" value={join(p.companySizes)}/><Field label="Travel preference" name="travelPreference" value={p.travelPreference ?? ""}/><label className="text-sm text-[#565c62]">Salary currency<input name="salaryCurrency" maxLength={3} defaultValue={p.salaryCurrency ?? ""} placeholder="EUR" className={inputClass}/></label><label className="text-sm text-[#565c62]">Minimum salary<input name="salaryMinimum" type="number" min="0" defaultValue={p.salaryMinimum ?? ""} className={inputClass}/></label><label className="text-sm text-[#565c62]">Maximum salary<input name="salaryMaximum" type="number" min="0" defaultValue={p.salaryMaximum ?? ""} className={inputClass}/></label><div className="md:col-span-2"><button className="rounded-xl bg-[#17191c] px-5 py-3 text-sm font-semibold text-white">Save my preferences</button></div></form></section>;
}
const inputClass = "mt-2 w-full rounded-xl border border-[#d9dcde] bg-white px-4 py-3 text-sm text-[#17191c]";
function Field({ label, name, value }: { label: string; name: string; value: string }) { return <label className="text-sm text-[#565c62]">{label}<input name={name} defaultValue={value} placeholder="Separate multiple choices with commas" className={inputClass}/></label>; }
function Source({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#dfe5e0] bg-[#f8faf8] p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#55705d]">{label}</p><p className="mt-2 text-sm text-[#30343a]">{value}</p></div>; }
