import { LiveWorkspaceEmptyState } from "@/components/live-workspace-empty-state";
import { ProductivityWorkspace } from "@/components/productivity/productivity-workspace";
import Link from "next/link";
import { resolveAuthenticatedRepositoryContext } from "@/lib/auth/repository-context";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { loadLatestCollectedDecision } from "@/lib/live-collected-decision";

export default async function ProductivityPage() {
  if (process.env.NEXT_PUBLIC_DATA_ACCESS_MODE === "supabase") {const resolved=await resolveAuthenticatedRepositoryContext();const decision=resolved?await loadLatestCollectedDecision(createServerSupabaseClient(resolved.accessToken),resolved.context.workspace!.workspaceId):undefined;if(!decision)return <LiveWorkspaceEmptyState title="Today" description="A focused view of confirmed priorities, preparation, and follow ups." emptyTitle="Your brief will begin with confirmed context" emptyDescription="Finalize an opportunity decision and its evidence will shape Today." actionHref="/opportunities" actionLabel="Explore opportunities" />;return <main className="mx-auto max-w-5xl px-5 py-8 sm:px-6 lg:px-10"><p className="text-sm uppercase tracking-[.18em] text-blue-300">Today</p><h1 className="mt-3 text-3xl font-semibold">Your {decision.action} decision is now in motion</h1><p className="mt-3 max-w-2xl text-slate-400">Atlas preserved the evidence and created the next appropriate action without changing your underlying facts.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><p className="text-xs uppercase tracking-[.14em] text-slate-500">Opportunity</p><h2 className="mt-3 text-xl font-semibold">{decision.title}</h2><p className="mt-1 text-slate-400">{decision.companyName}</p></article><article className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><p className="text-xs uppercase tracking-[.14em] text-slate-500">Next action</p><h2 className="mt-3 text-xl font-semibold">{decision.task.title}</h2><p className="mt-1 text-slate-400">{decision.task.status} · {decision.task.priority}</p></article></div><div className="mt-6 flex gap-4"><Link href={`/opportunities/${encodeURIComponent(decision.opportunityId)}`} className="text-sm font-medium text-blue-300">Review evidence →</Link><Link href="/archive" className="text-sm font-medium text-blue-300">Open Career Ledger →</Link></div></main>}
  return <ProductivityWorkspace />;
}
