import Link from "next/link";
import { OrendalisMark } from "@/components/brand/orendalis-mark";
import type { Locale } from "@/lib/locale";

export function AuthFrame({ eyebrow, title, description, children, footer, locale: _locale = "en" }: { eyebrow: string; title: string; description: string; children: React.ReactNode; footer?: React.ReactNode; locale?: Locale }) {
  void _locale;
  return <main className="orendalis-grid flex min-h-screen items-center justify-center bg-[#07101f] px-6 py-12 text-[#0b1220]"><section className="w-full max-w-md"><div className="mb-8 flex items-center justify-center"><Link href="/" className="inline-flex rounded-xl bg-white px-3 py-2 shadow-lg"><OrendalisMark /></Link></div><div className="rounded-[1.75rem] border border-white/80 bg-white p-7 shadow-[0_28px_90px_rgba(2,8,23,.32)] sm:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#3457d5]">{eyebrow}</p><h1 className="orendalis-display mt-4 text-4xl leading-tight tracking-[-0.045em]">{title}</h1><p className="mt-4 text-sm leading-6 text-[#5f6b7a]">{description}</p><div className="mt-8">{children}</div>{footer && <div className="mt-7 border-t border-[#dfe5ee] pt-6 text-sm text-[#5f6b7a]">{footer}</div>}</div><p className="mt-6 text-center text-xs leading-5 text-[#9cabc0]">Private by design. Your judgment remains yours.</p></section></main>;
}
export function AuthField({label,name,type="text",required=true,autoComplete,placeholder,defaultValue,readOnly=false}:{label:string;name:string;type?:string;required?:boolean;autoComplete?:string;placeholder?:string;defaultValue?:string;readOnly?:boolean}){return <label className="block text-sm font-medium text-[#263246]">{label}<input name={name} type={type} required={required} autoComplete={autoComplete} placeholder={placeholder} defaultValue={defaultValue} readOnly={readOnly} className="mt-2 w-full rounded-xl border border-[#d7deea] bg-white px-4 py-3 text-[#0b1220] outline-none transition placeholder:text-[#8c98aa] read-only:cursor-not-allowed read-only:text-[#6f7c8e] focus:border-[#6d8cff] focus:ring-2 focus:ring-[#6d8cff]/20"/></label>}
export function SubmitButton({children}:{children:React.ReactNode}){return <button className="w-full rounded-xl bg-[#0b1220] px-4 py-3 text-sm font-semibold text-white shadow-[0_8px_20px_rgba(11,18,32,.14)] transition hover:-translate-y-px hover:bg-[#18243a] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3457d5]">{children}</button>}
export function FormMessage({message,tone="error"}:{message?:string;tone?:"error"|"success"}){return message?<p role="status" className={`mb-5 rounded-xl border px-4 py-3 text-sm ${tone==="error"?"border-rose-200 bg-rose-50 text-rose-800":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{message}</p>:null}
