import { calculateAtlasConfidence } from "./confidence-engine";import { detectAtlasConflicts } from "./conflict-engine";import type { AtlasAssessment,AtlasConfidence,AtlasContext,AtlasDecision,AtlasDecisionCategory,AtlasDecisionEngine,AtlasDecisionExplanation,AtlasDecisionResult,AtlasDecisionSnapshot,AtlasEvidence,AtlasReasoningChain,AtlasRecommendation,AtlasScenario,AtlasSimulation,CareerCapitalImpact } from "./types";
const ENGINE_VERSION="12.0.0",RULESET_VERSION="1.0.0";
function evidence(id:string,category:AtlasEvidence["category"],weight:number,confidence:number,timestamp:string,source:string,type:string,entityId:string,reasonCode:string,ledgerEntryId?:string):AtlasEvidence{return{id,category,weight,confidence,timestamp,source,entity:{type,id:entityId},reasonCode,ledgerEntryId}}
function capitalImpact(context:AtlasContext):{impact:CareerCapitalImpact;factors:string[]}{const o=context.subject.opportunity;const factors:string[]=[];if(o.strategicOpportunityScore>=85)factors.push("STRATEGIC_RELEVANCE_HIGH");if(o.executiveFitScore>=85)factors.push("EXECUTIVE_FIT_HIGH");if(o.jobTitle.toLowerCase().includes("chief")||o.jobTitle.toLowerCase().includes("svp"))factors.push("LEADERSHIP_SCOPE_EXPANDS");if(o.riskFlags.length>1)factors.push("MATERIAL_RISK_FLAGS");const positive=factors.filter(x=>x.endsWith("HIGH")||x.endsWith("EXPANDS")).length,negative=factors.filter(x=>x.includes("RISK")).length;return{impact:positive>=3&&negative===0?"Strong Positive":positive>negative?"Positive":negative>positive?"Negative":"Neutral",factors}}
export class DeterministicAtlasDecisionEngine implements AtlasDecisionEngine{
collect(c:AtlasContext):readonly AtlasEvidence[]{const o=c.subject.opportunity,items:AtlasEvidence[]=[evidence("ev-blueprint","Executive Blueprint",100,c.blueprintCompleteness.score,c.blueprint.lastConfirmedAt,"Executive Blueprint","Blueprint",c.blueprint.id,"BLUEPRINT_REVISION_ACTIVE"),evidence("ev-opportunity","Opportunity",90,o.confidenceScore,o.discoveredAt,o.source,"Opportunity",o.id,"OPPORTUNITY_RECORD"),...c.ledger.slice(0,5).map((x,i)=>evidence(`ev-ledger-${i}`,"Career Ledger",70,x.confidence,x.occurredAt,x.sourceType,x.entityType,x.entityId,"LEDGER_EVENT",x.id))];if(c.subject.company)items.push(evidence("ev-company","Company",80,c.subject.company.companyQualityScore,c.subject.company.lastReviewedAt,c.subject.company.sourceStatus,"Company",c.subject.company.id,"COMPANY_PROFILE"));if(c.subject.compensation.length)items.push(evidence("ev-compensation","Compensation",90,c.subject.compensation[0].sourceConfidence,c.subject.compensation[0].recordedAt,c.subject.compensation[0].source,"Compensation",c.subject.compensation[0].id,"COMPENSATION_RECORD"));for(const p of c.blueprint.principles)items.push(evidence(`ev-principle-${p.id}`,"Executive Principle",100,100,c.blueprint.lastConfirmedAt,"Executive Blueprint","Principle",p.id,"NON_NEGOTIABLE_PRINCIPLE"));return items;}
normalize(c:AtlasContext):AtlasContext{return{...c,ledger:[...c.ledger].sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)),signals:[...c.signals].sort((a,b)=>a.observedAt.localeCompare(b.observedAt))}}
evaluate(c:AtlasContext,e:readonly AtlasEvidence[]):AtlasAssessment{const conflicts=detectAtlasConflicts(c,e),o=c.subject.opportunity,missing:string[]=[];if(o.salaryMin===undefined&&o.salaryMax===undefined)missing.push("COMPENSATION_RANGE");if(!c.subject.applications.some(a=>a.recruiterId))missing.push("RECRUITER_IDENTITY");if(!c.signals.some(s=>s.kind==="market"))missing.push("MARKET_SIGNAL");const cc=capitalImpact(c);const risks=o.riskFlags.map((x,i)=>({id:`risk-${i}`,code:x.toUpperCase().replace(/\W+/g,"_"),severity:"warning" as const,evidenceIds:["ev-opportunity"],mitigationCode:"VERIFY_BEFORE_DECISION"}));return{alignmentScore:o.overallScore,careerCapitalImpact:cc.impact,careerCapitalFactors:cc.factors,reasons:[{code:"EXECUTIVE_FIT",factor:"executive-fit-score",direction:o.executiveFitScore>=75?"supports":"opposes",importance:"high",evidenceIds:["ev-opportunity"]},{code:"STRATEGIC_VALUE",factor:"strategic-opportunity-score",direction:o.strategicOpportunityScore>=75?"supports":"opposes",importance:"high",evidenceIds:["ev-opportunity"]}],conflicts,risks,missingInformation:missing}}
score(c:AtlasContext,a:AtlasAssessment,e:readonly AtlasEvidence[]):AtlasConfidence{return calculateAtlasConfidence(c,a,e)}
rank(ds:readonly AtlasDecision[]):readonly AtlasDecision[]{return[...ds].sort((a,b)=>b.assessment.alignmentScore-a.assessment.alignmentScore||b.confidence.score-a.confidence.score)}
recommend(a:AtlasAssessment,c:AtlasConfidence):AtlasRecommendation{let category:AtlasDecisionCategory;if(a.conflicts.some(x=>x.severity==="critical"))category="Reject";else if(c.level==="Very Low"||c.level==="Low"||a.missingInformation.length>=3)category="Need More Information";else if(a.alignmentScore>=88&&c.score>=60)category="Strong Apply";else if(a.alignmentScore>=75)category="Apply";else if(a.risks.length)category="Review Carefully";else category="Monitor";return{category,reasonCodes:[...a.reasons.map(r=>r.code),...a.conflicts.map(x=>x.whyCode)],nextActionCodes:category==="Need More Information"?["COLLECT_MISSING_INFORMATION"]:category==="Reject"?["RECORD_REJECTION_REASON"]:["REVIEW_DECISION_WITH_EXECUTIVE"]}}
explain(d:AtlasDecision,c:AtlasContext):AtlasDecisionExplanation{return{why:d.recommendation.reasonCodes,whyNow:["OPPORTUNITY_ACTIVE","BLUEPRINT_REVISION_AVAILABLE"],whyNot:d.assessment.conflicts.map(x=>x.whyCode),whatChanged:c.historicalDecisions.length?["COMPARE_WITH_PREVIOUS_SNAPSHOT"]:["INITIAL_DECISION"],evidenceIds:d.evidence.map(e=>e.id),assumptionCodes:["CURRENCY_COMPARISON_ONLY_WHEN_EQUAL"],conflictIds:d.assessment.conflicts.map(x=>x.id),missingInformation:d.assessment.missingInformation}}
snapshot(d:AtlasDecision,c:AtlasContext,chain:AtlasReasoningChain):AtlasDecisionSnapshot{return{id:`snapshot-${d.id}`,timestamp:c.evaluatedAt,blueprintRevisionId:c.blueprint.revisionId,evidence:d.evidence,reasoningChain:chain,confidence:d.confidence,conflicts:d.assessment.conflicts,inputs:{opportunityId:c.subject.opportunity.id,companyId:c.subject.company?.id??null,blueprintId:c.blueprint.id},recommendation:d.recommendation,decisionVersion:{engineVersion:ENGINE_VERSION,rulesetVersion:RULESET_VERSION,normalizationVersion:"1.0.0"}}}
run(input:AtlasContext):AtlasDecisionResult{const c=this.normalize(input),e=this.collect(c),a=this.evaluate(c,e),confidence=this.score(c,a,e),recommendation=this.recommend(a,confidence),decision:AtlasDecision={id:`decision-${c.subject.opportunity.id}-${c.blueprint.revisionId}`,contextId:c.id,category:recommendation.category,assessment:a,confidence,evidence:e,recommendation,createdAt:c.evaluatedAt,version:ENGINE_VERSION};const chain:AtlasReasoningChain=["Reason","Evidence","Assessment","Conflict Review","Confidence","Decision","Recommendation","Snapshot"].map((stage,i)=>({order:i+1,stage:stage as AtlasReasoningChain[number]["stage"],artifactIds:i===1?e.map(x=>x.id):i===3?a.conflicts.map(x=>x.id):[decision.id],status:"completed"}));return{decision,explanation:this.explain(decision,c),snapshot:this.snapshot(decision,c,chain),reasoningChain:chain}}
simulate(context:AtlasContext,scenario:AtlasScenario):AtlasSimulation{const baseline=this.run(context).snapshot;const opportunity={...context.subject.opportunity};if(typeof scenario.changes.salaryMin==="number")opportunity.salaryMin=scenario.changes.salaryMin;if(typeof scenario.changes.salaryMax==="number")opportunity.salaryMax=scenario.changes.salaryMax;if(typeof scenario.changes.travelRequirement==="string")opportunity.travelRequirement=scenario.changes.travelRequirement;if(typeof scenario.changes.country==="string")opportunity.country=scenario.changes.country;const result=this.run({...context,id:`${context.id}-${scenario.id}`,subject:{...context.subject,opportunity},historicalDecisions:[...context.historicalDecisions,baseline]}).snapshot;return{id:`simulation-${scenario.id}`,scenario,baseline,result,changedDecision:baseline.recommendation.category!==result.recommendation.category,changedReasonCodes:result.recommendation.reasonCodes.filter(x=>!baseline.recommendation.reasonCodes.includes(x)),createdAt:context.evaluatedAt}}
}
