import type { Application } from "@/types/application";import type { CareerLedgerEntry,SerializableValue } from "@/types/career-ledger";import type { Company } from "@/types/company";import type { CompensationRecord } from "@/types/compensation";import type { BlueprintCompleteness,ExecutiveBlueprint } from "@/types/executive-blueprint";import type { Opportunity } from "@/types/opportunity";import type { DiscoveryRun } from "@/lib/discovery";
export type AtlasEvidenceCategory="Executive Blueprint"|"Career Ledger"|"Compensation"|"Company"|"Opportunity"|"Application"|"Discovery"|"Historical Decision"|"Executive Principle"|"Career Objective"|"Market Signal"|"Future Provider"|"Unknown";export type AtlasConfidenceLevel="Very Low"|"Low"|"Moderate"|"High"|"Very High";export type AtlasDecisionCategory="Apply"|"Strong Apply"|"Review Carefully"|"Wait"|"Monitor"|"Network First"|"Negotiate"|"Reject"|"Archive"|"Need More Information";export type AtlasConflictSeverity="information"|"warning"|"critical";export type CareerCapitalImpact="Strong Positive"|"Positive"|"Neutral"|"Negative"|"Strong Negative";
export interface AtlasEvidence{id:string;category:AtlasEvidenceCategory;weight:number;confidence:number;timestamp:string;source:string;entity:{type:string;id:string};reasonCode:string;ledgerEntryId?:string}
export interface AtlasReason{code:string;factor:string;direction:"supports"|"opposes"|"unknown";importance:"low"|"medium"|"high"|"critical";evidenceIds:readonly string[]}
export interface AtlasConfidence{level:AtlasConfidenceLevel;score:number;factors:readonly {code:string;impact:number;value:number;reason:string}[]}
export interface AtlasConstraint{id:string;source:"Blueprint"|"Principle"|"Application"|"System";field:string;operator:"minimum"|"maximum"|"requires"|"excludes";value:string;nonNegotiable:boolean}
export interface AtlasConflict{id:string;type:"salary"|"travel"|"industry"|"company-size"|"board"|"leadership"|"language"|"compensation"|"blueprint"|"risk"|"career-principle";severity:AtlasConflictSeverity;whyCode:string;constraintId?:string;evidenceIds:readonly string[];possibleResolutionCode:string}
export interface AtlasSignal{id:string;kind:string;value:SerializableValue;observedAt:string;evidenceId?:string}
export interface AtlasInsight{id:string;code:string;evidenceIds:readonly string[];decisionRelevance:"low"|"medium"|"high"}
export interface AtlasRisk{id:string;code:string;severity:AtlasConflictSeverity;evidenceIds:readonly string[];mitigationCode:string}
export interface AtlasOpportunity{opportunity:Opportunity;company?:Company;applications:readonly Application[];compensation:readonly CompensationRecord[];discoveryRuns:readonly DiscoveryRun[]}
export interface AtlasContext{id:string;evaluatedAt:string;blueprint:ExecutiveBlueprint;blueprintCompleteness:BlueprintCompleteness;ledger:readonly CareerLedgerEntry[];subject:AtlasOpportunity;signals:readonly AtlasSignal[];historicalDecisions:readonly AtlasDecisionSnapshot[];workspace?:{context:import("@/lib/workspaces").WorkspaceContext;currentWorkspaceId:string;currentExecutiveId:string;language:string;timezone:string;capabilities:readonly string[];permissionScope:readonly import("@/lib/workspaces").WorkspacePermission[];currentBlueprintRevisionId:string;knowledgeSnapshotId?:string;decisionSnapshotId?:string};knowledge?:{snapshot:import("@/lib/knowledge").KnowledgeSnapshot;relevantSignals:readonly import("@/lib/knowledge").KnowledgeSignal[];confidence:import("@/lib/knowledge").KnowledgeConfidence;relationships:readonly import("@/lib/knowledge").KnowledgeRelationship[];evidence:readonly import("@/lib/knowledge").KnowledgeEvidence[];digest?:import("@/lib/knowledge").KnowledgeDigest};engineVersion:string}
export interface AtlasAssessment{alignmentScore:number;careerCapitalImpact:CareerCapitalImpact;careerCapitalFactors:readonly string[];reasons:readonly AtlasReason[];conflicts:readonly AtlasConflict[];risks:readonly AtlasRisk[];missingInformation:readonly string[]}
export interface AtlasRecommendation{category:AtlasDecisionCategory;reasonCodes:readonly string[];nextActionCodes:readonly string[]}
export interface AtlasDecision{id:string;contextId:string;category:AtlasDecisionCategory;assessment:AtlasAssessment;confidence:AtlasConfidence;evidence:readonly AtlasEvidence[];recommendation:AtlasRecommendation;createdAt:string;version:string}
export interface AtlasDecisionTree{id:string;root:string;nodes:readonly {id:string;conditionCode:string;trueNode?:string;falseNode?:string;outcome?:AtlasDecisionCategory}[]}
export interface AtlasDecisionExplanation{why:readonly string[];whyNow:readonly string[];whyNot:readonly string[];whatChanged:readonly string[];evidenceIds:readonly string[];assumptionCodes:readonly string[];conflictIds:readonly string[];missingInformation:readonly string[]}
export interface AtlasReasoningStep{order:number;stage:"Reason"|"Evidence"|"Assessment"|"Conflict Review"|"Confidence"|"Decision"|"Recommendation"|"Snapshot";artifactIds:readonly string[];status:"completed"|"blocked"}
export type AtlasReasoningChain=readonly AtlasReasoningStep[];export interface AtlasDecisionVersion{engineVersion:string;rulesetVersion:string;normalizationVersion:string}
export interface AtlasDecisionSnapshot{id:string;timestamp:string;blueprintRevisionId:string;evidence:readonly AtlasEvidence[];reasoningChain:AtlasReasoningChain;confidence:AtlasConfidence;conflicts:readonly AtlasConflict[];inputs:Readonly<Record<string,SerializableValue>>;recommendation:AtlasRecommendation;decisionVersion:AtlasDecisionVersion}
export interface AtlasDecisionHistory{subjectId:string;snapshots:readonly AtlasDecisionSnapshot[]}
export interface AtlasScenario{id:string;name:string;changes:Readonly<Record<string,SerializableValue>>;baselineSnapshotId?:string}
export interface AtlasSimulation{id:string;scenario:AtlasScenario;baseline:AtlasDecisionSnapshot;result:AtlasDecisionSnapshot;changedDecision:boolean;changedReasonCodes:readonly string[];createdAt:string}
export interface AtlasDecisionResult{decision:AtlasDecision;explanation:AtlasDecisionExplanation;snapshot:AtlasDecisionSnapshot;reasoningChain:AtlasReasoningChain}
export interface AtlasDecisionEngine{collect(context:AtlasContext):readonly AtlasEvidence[];normalize(context:AtlasContext):AtlasContext;evaluate(context:AtlasContext,evidence:readonly AtlasEvidence[]):AtlasAssessment;score(context:AtlasContext,assessment:AtlasAssessment,evidence:readonly AtlasEvidence[]):AtlasConfidence;rank(decisions:readonly AtlasDecision[]):readonly AtlasDecision[];recommend(assessment:AtlasAssessment,confidence:AtlasConfidence):AtlasRecommendation;explain(decision:AtlasDecision,context:AtlasContext):AtlasDecisionExplanation;snapshot(decision:AtlasDecision,context:AtlasContext,chain:AtlasReasoningChain):AtlasDecisionSnapshot;run(context:AtlasContext):AtlasDecisionResult;simulate(context:AtlasContext,scenario:AtlasScenario):AtlasSimulation}
export interface AtlasFutureProviderBoundary{explain(snapshot:AtlasDecisionSnapshot):Promise<string>;summarize(history:AtlasDecisionHistory):Promise<string>;generateReport(snapshot:AtlasDecisionSnapshot):Promise<string>;prepareInterview(snapshot:AtlasDecisionSnapshot):Promise<string>;draftCoverLetter(snapshot:AtlasDecisionSnapshot):Promise<string>;suggestCVImprovements(snapshot:AtlasDecisionSnapshot):Promise<readonly string[]>}
