import { redirect } from "next/navigation";
import { PageContent } from "@/components/page-content";
import { PageHeader } from "@/components/page-header";
import { SectionCard } from "@/components/section-card";
import { StatusBadge } from "@/components/status-badge";
import { resolveAuthenticatedRepositoryContext } from "@/lib/auth/repository-context";
import { SupabaseBetaWorkflowRepository } from "@/lib/beta/repository";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { finalizeDecisionAction, runReasoningAction, saveBlueprintAction, saveHistoryAction, saveOpportunityAction, submitFeedbackAction, submitLifecycleAction } from "./actions";

const field="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-blue-400";const button="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400";
function Input({label,name,type="text",required=true}:{label:string;name:string;type?:string;required?:boolean}){return <label className="text-sm text-slate-300">{label}<input className={field} name={name} type={type} required={required}/></label>}
function TextArea({label,name,required=false}:{label:string;name:string;required?:boolean}){return <label className="text-sm text-slate-300">{label}<textarea className={`${field} min-h-24`} name={name} required={required}/></label>}
function Submit({children}:{children:React.ReactNode}){return <button className={button}>{children}</button>}
export default async function BetaWorkflowPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const [resolved,q]=await Promise.all([resolveAuthenticatedRepositoryContext(),searchParams]);if(!resolved)redirect("/login?next=/beta-workflow");const repo=new SupabaseBetaWorkflowRepository(createServerSupabaseClient(resolved.accessToken),resolved.context);let view;try{view=await repo.load();}catch(error){return <PageContent><PageHeader eyebrow="Private beta" title="Workflow unavailable" description={error instanceof Error?error.message:"The workflow could not be loaded."}/></PageContent>}const complete=new Set(view.state.completedSteps);return <PageContent><PageHeader eyebrow="Release 0.6 · Invitation only" title="Executive Opportunity Decision" description="A durable, evidence-led workflow. Saved stages are Workspace-scoped and survive refresh, logout, and return."/><div className="mb-6 flex flex-wrap gap-2">{["Invitation","Onboarding","Professional History","Blueprint","Opportunity","Reasoning","Decision Finalized","Feedback","Lifecycle"].map(step=><StatusBadge key={step} tone={complete.has(step)?"success":"neutral"}>{step}: {complete.has(step)?"Complete":"Pending"}</StatusBadge>)}</div>{q.error&&<p role="alert" className="mb-6 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{q.error}</p>}
<div className="grid gap-6 xl:grid-cols-2"><SectionCard><h2 className="text-xl font-semibold">1. Essential professional history</h2><p className="mt-2 text-sm text-slate-400">Manual entry is confirmed immediately. Raw source documents are not retained.</p><form action={saveHistoryAction} className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Organization" name="organizationName"/><Input label="Executive role" name="roleTitle"/><Input label="Start date" name="startDate" type="date" required={false}/><Input label="End date" name="endDate" type="date" required={false}/><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" name="isCurrent"/>Current role</label><div/><div className="sm:col-span-2"><TextArea label="Notes (optional)" name="notes"/></div><Submit>Confirm history record</Submit></form><p className="mt-4 text-xs text-slate-500">Persisted records: {view.historyCount}</p></SectionCard>
<SectionCard><h2 className="text-xl font-semibold">2. Minimum Executive Blueprint</h2><form action={saveBlueprintAction} className="mt-5 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><TextArea label="Career vision" name="careerVision" required/></div><TextArea label="Preferred industries — one per line" name="preferredIndustries"/><TextArea label="Preferred countries — one per line" name="preferredCountries"/><Input label="Minimum compensation" name="minimumCompensation" type="number" required={false}/><Input label="Currency (ISO 4217)" name="currency" required={false}/><Input label="Maximum travel %" name="maximumTravelPercent" type="number" required={false}/><Input label="Leadership level" name="leadershipLevel"/><div className="sm:col-span-2"><TextArea label="Constraints — one per line" name="constraints"/></div><Submit>Save confirmed revision</Submit></form><p className="mt-4 text-xs text-slate-500">Active revision: {view.state.activeBlueprintRevisionId??"Not created"}</p></SectionCard>
<SectionCard><h2 className="text-xl font-semibold">3. Opportunity context</h2><form action={saveOpportunityAction} className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Role title" name="title"/><Input label="Company" name="companyName"/><Input label="Location" name="location"/><Input label="Work model" name="workModel"/><Input label="Source" name="source"/><Input label="Recruiter context" name="recruiterContext" required={false}/><Input label="Compensation minimum" name="compensationMin" type="number" required={false}/><Input label="Compensation maximum" name="compensationMax" type="number" required={false}/><Input label="Currency" name="currency" required={false}/><div/><TextArea label="Known facts — one per line" name="knownFacts"/><TextArea label="Unverified claims — one per line" name="unverifiedClaims"/><TextArea label="Constraints — one per line" name="constraints"/><TextArea label="Notes" name="notes"/><Submit>Save opportunity</Submit></form><p className="mt-4 text-xs text-slate-500">Active opportunity: {view.state.activeOpportunityId??"Not created"}</p></SectionCard>
<SectionCard><h2 className="text-xl font-semibold">4. Atlas assessment and decision</h2><p className="mt-2 text-sm text-slate-400">Atlas loads only the active persisted Blueprint revision, confirmed history, opportunity, and entered compensation. Unknowns remain unknown.</p><form action={runReasoningAction} className="mt-5"><Submit>Run deterministic assessment</Submit></form>{view.reasoning&&<pre className="mt-5 max-h-72 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-300">{JSON.stringify(view.reasoning.output,null,2)}</pre>}<form action={finalizeDecisionAction} className="mt-5 grid gap-4"><label className="text-sm text-slate-300">Selected next action<select className={field} name="selectedAction">{["Apply","Wait","Reject","Monitor","Negotiate","Network First"].map(value=><option key={value}>{value}</option>)}</select></label><input type="hidden" name="idempotencyKey" value={view.state.activeReasoningSnapshotId??""}/><Submit>Finalize immutable decision</Submit></form><p className="mt-4 text-xs text-slate-500">Decision commit: {view.state.finalizedDecisionId??"Not finalized"}</p></SectionCard>
<SectionCard><h2 className="text-xl font-semibold">5. Structured beta feedback</h2><form action={submitFeedbackAction} className="mt-5 grid gap-4"><input type="hidden" name="workflowStep" value={view.state.currentStep}/><label className="text-sm text-slate-300">Category<select className={field} name="category">{["Bug","Confusion","Friction","Missing Information","Trust Concern","Incorrect Assessment","Useful Insight","Feature Request","Performance","Accessibility","Privacy","Security"].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm text-slate-300">Severity<select className={field} name="severity">{["Low","Medium","High","Critical"].map(value=><option key={value}>{value}</option>)}</select></label><TextArea label="What happened?" name="description" required/><TextArea label="Expected behavior" name="expectedBehavior"/><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" name="consentToFollowUp"/>Founder may follow up</label><Submit>Submit private feedback</Submit></form><p className="mt-4 text-xs text-slate-500">Your submissions: {view.feedbackCount}</p></SectionCard>
<SectionCard><h2 className="text-xl font-semibold">6. Data lifecycle request</h2><p className="mt-2 text-sm text-slate-400">Requests are founder-supervised. Append-only decision history and security audit records may require a documented retention exception; this interface does not promise instant hard deletion.</p><form action={submitLifecycleAction} className="mt-5 grid gap-4"><label className="text-sm text-slate-300">Request type<select className={field} name="requestType">{["Export","Account Closure","Deletion","Consent Withdrawal"].map(value=><option key={value}>{value}</option>)}</select></label><TextArea label="Optional note" name="userNote"/><Submit>Submit reviewed request</Submit></form><div className="mt-4 space-y-2 text-xs text-slate-400">{view.lifecycleRequests.map(request=><p key={String(request.id)}>{String(request.request_type)} · {String(request.status)} · {String(request.retention_status)}</p>)}</div></SectionCard></div></PageContent>}
