import { validateImportFile, sanitizeFilename } from "../lib/import/file-policy.ts";
import { extractHistory } from "../lib/import/extraction.ts";
import { detectHistoryConflicts } from "../lib/import/conflicts.ts";
import { createFirstExecutiveBrief } from "../lib/import/brief.ts";
import { detectHistoryDrafts } from "../lib/import/history-drafts.ts";

const provenance={source:"CSV",filename:"fictional.csv",importedAt:"2026-01-01T00:00:00Z",importVersion:"1.0",evidence:[]};
const result=extractHistory("CSV","company,title,start,end\nExample Group,Chief Test Officer,2020-01,2023-01\nExample Group,Chief Test Officer,2020-01,2023-01",provenance);
if(result.experiences.length!==2)throw Error("CSV extraction failed");
if(!detectHistoryConflicts(result.experiences).some(c=>c.type==="Duplicate role"))throw Error("Duplicate conflict missing");
if(validateImportFile({name:"payload.exe",size:10}).ok)throw Error("Executable accepted");
if(validateImportFile({name:"large.csv",size:6*1024*1024}).ok)throw Error("Oversized file accepted");
if(sanitizeFilename("../../sensitive?.csv").includes(".."))throw Error("Filename not sanitized");
const bad=extractHistory("Structured JSON","{bad",provenance);
if(!bad.warnings.length)throw Error("Parser failure not safe");
result.experiences[1].decision="Reject";
const brief=createFirstExecutiveBrief(result.experiences,[]);
if(!brief.facts[0].startsWith("1 confirmed"))throw Error("Review rejection ignored");
const resumeDrafts=detectHistoryDrafts("Chief Strategy Officer\nAurora Meridian Group\nMarch 2022 - Present");
if(resumeDrafts.length!==1||resumeDrafts[0].roleTitle!=="Chief Strategy Officer"||resumeDrafts[0].organizationName!=="Aurora Meridian Group"||resumeDrafts[0].startDate!=="2022-03"||!resumeDrafts[0].isCurrent)throw Error("Resume history extraction failed");
console.log("PASS Import validation — deterministic CV draft extraction, CSV extraction, safe rejection, conflicts, review decisions, sanitization, and deterministic brief");
