"use client";

import { useState } from "react";

type LinkRecord={id:string;status:string;expires_at:string;max_uses:number;use_count:number};

export function RoomInviteLinkManager({roomId,links}:{roomId:string;links:LinkRecord[]}) {
  const [shareUrl,setShareUrl]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function createLink(){setBusy(true);setMessage("");const response=await fetch("/api/rooms/invite-links",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({roomId,maxUses:25})});const body=await response.json();setBusy(false);if(!response.ok){setMessage(body.error??"Link could not be created");return;}setShareUrl(body.shareUrl);setMessage("Secure link created. It expires in 7 days and can be revoked.");}
  async function revoke(linkId:string){setBusy(true);const response=await fetch("/api/rooms/invite-links",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({linkId})});setBusy(false);if(response.ok) location.reload();else setMessage("Link could not be revoked.");}
  return <section className="rounded-2xl border border-[#dfe5ee] bg-white p-5"><h2 className="text-lg font-semibold text-[#0b1220]">Invite executives securely</h2><p className="mt-2 text-sm leading-6 text-[#5f6b7a]">Create a private link and share it directly. The secret stays after the # sign, so it is not sent in page requests or server logs.</p><button type="button" disabled={busy} onClick={createLink} className="mt-4 rounded-full bg-[#0b1220] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Working…":"Create invitation link"}</button>{shareUrl&&<div className="mt-4 rounded-xl bg-[#f4f7fa] p-4"><label className="text-xs font-semibold uppercase tracking-wide text-[#63758b]">Share this link</label><div className="mt-2 flex gap-2"><input readOnly value={shareUrl} className="min-w-0 flex-1 rounded-lg border border-[#cbd3dc] bg-white px-3 py-2 text-sm"/><button type="button" onClick={()=>navigator.clipboard.writeText(shareUrl)} className="rounded-lg border border-[#cbd3dc] px-3 text-sm font-semibold">Copy</button></div></div>}{message&&<p role="status" className="mt-3 text-sm text-[#526070]">{message}</p>}{links.length>0&&<div className="mt-5 space-y-2">{links.map(link=><div key={link.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#e3e7eb] px-3 py-2 text-xs"><span>{link.status} · {link.use_count}/{link.max_uses} joined · expires {new Date(link.expires_at).toLocaleDateString("en")}</span>{link.status==="Active"&&<button type="button" disabled={busy} onClick={()=>revoke(link.id)} className="font-semibold text-[#8b3c34]">Revoke</button>}</div>)}</div>}</section>;
}
