import type { SerializableValue } from "@/types/career-ledger";
export const knowledgeCategories=["Company","Executive Search","Recruiter","Industry","Technology","Country","Economy","Compensation","Leadership","Board","Market","Hiring","Mergers","Funding","Expansion","Layoffs","Executive Appointment","Executive Departure","Policy","Regulation"] as const;export type KnowledgeCategory=typeof knowledgeCategories[number];
export type KnowledgeLifecycle="Observed"|"Verified"|"Updated"|"Superseded"|"Archived"|"Expired"|"Dismissed";export type KnowledgeConfidence="Very Low"|"Low"|"Moderate"|"High"|"Very High";export type KnowledgeSeverity="information"|"low"|"medium"|"high"|"critical";export type KnowledgeRelationshipStrength="weak"|"moderate"|"strong"|"direct";export type KnowledgeEntityType="Company"|"Opportunity"|"Application"|"Executive Blueprint"|"Career Objective"|"Career Principle"|"Industry"|"Country"|"Compensation"|"Career Ledger"|"Decision Snapshot"|"Discovery Run";
export interface KnowledgeVersion{schemaVersion:string;rulesetVersion:string;normalizationVersion:string}
export interface KnowledgeSource{id:string;name:string;providerId:string;reference?:string;observedAt:string;isDemo:true}
export interface KnowledgeProvider{id:string;name:string;kind:"Corporate Reports"|"Company Website"|"Executive Search Firm"|"Recruiter"|"Industry Publication"|"Market Research"|"Economic Data"|"Government"|"Manual Research"|"Atlas Observation"|"Internal Research";reliability:number;status:"stub";observe(topic:KnowledgeTopic):Promise<readonly KnowledgeObservation[]>;health():Promise<{available:boolean;message:string}>}
export interface KnowledgeEvidence{id:string;sourceId:string;weight:number;confidence:number;observedAt:string;reasonCode:string;entityId?:string;isDemo:true}
export interface KnowledgeEntity{id:string;type:KnowledgeEntityType;label:string}
export interface KnowledgeRelationship{id:string;signalId:string;entity:KnowledgeEntity;strength:KnowledgeRelationshipStrength;confidence:number;reasonCode:string}
export interface KnowledgeSignal{id:string;category:KnowledgeCategory;title:string;code:string;value:SerializableValue;severity:KnowledgeSeverity;lifecycle:KnowledgeLifecycle;observedAt:string;verifiedAt?:string;expiresAt?:string;providerId:string;evidenceIds:readonly string[];relationships:readonly KnowledgeRelationship[];conflictIds:readonly string[];missingInformation:readonly string[];isDemo:true}
export interface KnowledgeObservation{id:string;providerId:string;topicId:string;observedAt:string;payload:Readonly<Record<string,SerializableValue>>;sourceId:string;isDemo:true}
export interface KnowledgeImpact{id:string;signalId:string;entityId:string;direction:"positive"|"neutral"|"negative"|"unknown";magnitude:"low"|"medium"|"high";reasonCode:string}
export interface KnowledgeAssessment{id:string;signalId:string;confidence:KnowledgeConfidence;confidenceScore:number;factors:readonly KnowledgeConfidenceFactor[];impacts:readonly KnowledgeImpact[];conflicts:readonly string[];missingInformation:readonly string[]}
export interface KnowledgeConfidenceFactor{code:string;value:number;weight:number;reason:string}
export interface KnowledgeTopic{id:string;category:KnowledgeCategory;label:string;keywords:readonly string[];entityIds:readonly string[];isDemo:true}
export interface KnowledgeSubscription{id:string;watchlistId:string;topicId:string;frequency:"manual"|"daily"|"weekly";enabled:boolean;isDemo:true}
export interface KnowledgeWatchlist{id:string;name:string;kind:"Companies"|"Countries"|"Industries"|"Recruiters"|"Executive Search Firms"|"Technologies"|"Compensation Topics"|"Leadership Topics";topicIds:readonly string[];subscriptions:readonly KnowledgeSubscription[];isDemo:true}
export interface KnowledgeTimeline{id:string;entityId:string;events:readonly {signalId:string;occurredAt:string;lifecycle:KnowledgeLifecycle;code:string}[]}
export interface KnowledgeHistory{signalId:string;versions:readonly {lifecycle:KnowledgeLifecycle;changedAt:string;supersedesId?:string;reasonCode:string}[]}
export interface KnowledgeCorrelation{id:string;signalIds:readonly string[];strength:KnowledgeRelationshipStrength;reasonCode:string;confidence:number}
export interface KnowledgeTrend{id:string;topicId:string;direction:"increasing"|"stable"|"decreasing"|"insufficient-data";observationCount:number;confidence:KnowledgeConfidence;reasonCode:string}
export interface KnowledgeInsight{id:string;code:string;signalIds:readonly string[];relationshipIds:readonly string[];confidence:KnowledgeConfidence;isGenerated:false}
export interface KnowledgeRuleset{id:string;version:string;effectiveAt:string;ruleCodes:readonly string[]}
export interface KnowledgeSnapshot{id:string;createdAt:string;signals:readonly KnowledgeSignal[];assessments:readonly KnowledgeAssessment[];relationships:readonly KnowledgeRelationship[];watchlists:readonly KnowledgeWatchlist[];version:KnowledgeVersion;isDemo:true}
export interface KnowledgeDigest{id:string;snapshotId:string;createdAt:string;whatChanged:readonly string[];whyItMatters:readonly string[];affectedOpportunityIds:readonly string[];affectedCompanyIds:readonly string[];affectedBlueprintObjectiveIds:readonly string[];affectedCareerPrincipleIds:readonly string[];recommendedReviewCodes:readonly string[];isGenerated:false;isDemo:true}
