import Link from "next/link";
import { OrendalisMark } from "@/components/brand/orendalis-mark";
import { AtlasMark } from "@/components/atlas/atlas-mark";
import { LanguageSwitcher } from "@/components/language-switcher";
import { copy, type Locale } from "@/lib/locale";

export function ExperienceZeroArrival({ locale }: { locale: Locale }) {
  const t = copy[locale];
  return <main className="min-h-screen bg-[#f7f3ec] text-[#22211f]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 sm:px-10" aria-label="Primary navigation"><Link href="/" className="text-[#17191c]"><OrendalisMark /></Link><div className="flex items-center gap-3"><LanguageSwitcher locale={locale}/><Link href="/login" className="rounded-full px-4 py-2 text-sm font-medium text-[#4b5056] hover:bg-[#f3f4f4]">{t.signIn}</Link></div></nav>
    <section className="mx-auto grid min-h-[calc(100vh-88px)] max-w-7xl items-center gap-16 px-6 py-16 sm:px-10 lg:grid-cols-[1.08fr_.92fr] lg:py-24"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#936b3f]">{locale === "tr" ? "Yönetici fırsatlarına daha net bak" : "A clearer view of executive opportunity"}</p><h1 className="orendalis-display mt-6 max-w-4xl text-5xl leading-[1.02] tracking-[-.05em] text-[#22211f] sm:text-7xl">{t.hero}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#625d57]">{t.heroBody}</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/login?next=/opportunities" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#22211f] px-6 text-sm font-semibold text-white hover:bg-black">{t.searchJobs}</Link><Link href="/login?next=/import" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#d8d0c5] bg-[#fffdf9] px-6 text-sm font-semibold text-[#302d29] hover:bg-white">{t.uploadCv}</Link></div><p className="mt-5 text-sm text-[#817a72]">{locale === "tr" ? "Gizlilik en başından tasarlandı. Karar her zaman senin." : "Private by design. Your judgment always remains yours."}</p></div>
      <aside className="rounded-[2rem] border border-[#e3ddd3] bg-[#eee6da] p-6 shadow-[0_30px_80px_rgba(54,43,31,.08)] sm:p-8" aria-label="Atlas"><div className="rounded-2xl bg-[#fffdf9] p-6 shadow-sm ring-1 ring-black/[.04]"><div className="flex items-center gap-3"><AtlasMark/><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#936b3f]">{t.atlasTitle}</p></div><p className="mt-4 text-xl font-semibold leading-7">{t.atlasBody}</p><Link href="/login?next=/opportunities" className="mt-6 inline-flex text-sm font-semibold text-[#835c34]">{locale === "tr" ? "Önerileri incele →" : "Review recommendations →"}</Link></div></aside>
    </section>
    <section className="border-y border-[#e3ddd3] bg-[#fffdf9] px-6 py-24"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-semibold tracking-[-.03em]">{t.how}</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{t.steps.map((step, index) => <article key={step}><span className="text-sm font-semibold text-[#936b3f]">0{index + 1}</span><p className="mt-3 text-lg leading-7">{step}</p></article>)}</div></div></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-6 py-24 md:grid-cols-2"><div><AtlasMark size={48}/><h2 className="mt-5 text-3xl font-semibold tracking-[-.03em]">{t.control}</h2><p className="mt-4 leading-7 text-[#625d57]">{t.controlBody}</p></div><div className="rounded-3xl border border-[#e3ddd3] bg-[#faf6ef] p-8"><p className="text-lg leading-8 text-[#4d4741]">{locale === "tr" ? "Atlas kesinlik iddiasında bulunmaz. Bildiklerini, tahmin ettiklerini ve henüz bilmediklerini açıkça ayırır." : "Atlas never pretends to be certain. It separates what is known, what is estimated, and what still needs checking."}</p></div></section>
    <section className="border-t border-[#e3ddd3] bg-[#eee2d2] px-6 py-20 text-center text-[#22211f]"><h2 className="orendalis-display text-3xl tracking-[-.03em]">{t.final}</h2><div className="mt-7 flex justify-center gap-3"><Link href="/login?next=/opportunities" className="rounded-full bg-[#22211f] px-6 py-3 text-sm font-semibold text-white">{t.searchJobs}</Link><Link href="/login?next=/import" className="rounded-full border border-[#bda17f] bg-[#fffdf9] px-6 py-3 text-sm font-semibold">{t.uploadCv}</Link></div></section>
  </main>;
}
