export type BetaWorkflowStep = "Professional History" | "Blueprint" | "Opportunity" | "Reasoning" | "Decision" | "Feedback" | "Lifecycle" | "Complete";
export interface BetaWorkflowState { id:string; workspaceId:string; executiveIdentityId:string; currentStep:BetaWorkflowStep; completedSteps:string[]; activeBlueprintRevisionId?:string; activeOpportunityId?:string; activeReasoningSnapshotId?:string; finalizedDecisionId?:string; version:number }
export interface BetaHistoryInput { organizationName:string; roleTitle:string; startDate?:string; endDate?:string; isCurrent:boolean; notes?:string; sourceType?:"Manual Entry"|"Document Import"; sourceFilename?:string }
export interface BetaBlueprintInput { careerVision:string; preferredIndustries:string[]; preferredCountries:string[]; minimumCompensation?:number; currency?:string; maximumTravelPercent?:number; leadershipLevel:string; constraints:string[] }
export interface BetaOpportunityInput { title:string; companyName:string; location:string; workModel:string; source:string; recruiterContext?:string; compensationMin?:number; compensationMax?:number; currency?:string; constraints:string[]; knownFacts:string[]; unverifiedClaims:string[]; notes?:string }
export interface BetaFeedbackInput { route:string; workflowStep:string; category:string; severity:string; description:string; expectedBehavior?:string; consentToFollowUp:boolean }
export interface BetaLifecycleInput { requestType:"Export"|"Account Closure"|"Deletion"|"Consent Withdrawal"; userNote?:string }
export interface BetaReasoningPayload extends Record<string,unknown> { output:ReasoningOutput }
export interface BetaWorkflowView { state:BetaWorkflowState; historyCount:number; blueprint?:Record<string,unknown>; opportunity?:Record<string,unknown>; reasoning?:BetaReasoningPayload; feedbackCount:number; lifecycleRequests:Array<Record<string,unknown>> }
export interface FounderBetaTriage { feedback:Array<{id:string;category:string;severity:string;description:string;status:string;workflowStep:string;createdAt:string;consentToFollowUp:boolean}>; lifecycle:Array<{id:string;requestType:string;status:string;retentionStatus:string;submittedAt:string}> }
import type { ReasoningOutput } from "@/lib/reasoning";
