begin;
create extension if not exists pgcrypto;

create table public.executive_identities(id uuid primary key, auth_user_id uuid unique, profile jsonb not null default '{}', status text not null default 'Active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), version integer not null default 1 check(version>0));
create table public.workspaces(id uuid primary key, owner_identity_id uuid not null references public.executive_identities(id), name text not null, workspace_type text not null, status text not null default 'Active', plan text not null default 'Free', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references public.executive_identities(id), version integer not null default 1 check(version>0), archived_at timestamptz);
create table public.workspace_memberships(id uuid primary key, workspace_id uuid not null references public.workspaces(id), executive_identity_id uuid not null references public.executive_identities(id), role text not null, status text not null default 'Active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references public.executive_identities(id), version integer not null default 1 check(version>0), archived_at timestamptz, unique(workspace_id,executive_identity_id));
create table public.workspace_invitations(id uuid primary key, workspace_id uuid not null references public.workspaces(id), invited_email text, intended_role text not null, status text not null default 'Pending', expires_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references public.executive_identities(id), version integer not null default 1 check(version>0), archived_at timestamptz);
create table public.workspace_permissions(id uuid primary key, permission_key text not null unique, description text not null, created_at timestamptz not null default now());
create table public.workspace_member_permissions(id uuid primary key, workspace_id uuid not null references public.workspaces(id), membership_id uuid not null references public.workspace_memberships(id), permission_id uuid not null references public.workspace_permissions(id), effect text not null check(effect in ('Allow','Deny')), created_at timestamptz not null default now(), created_by uuid not null references public.executive_identities(id), unique(membership_id,permission_id));

create function public.is_active_workspace_member(target_workspace uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from workspace_memberships m join executive_identities i on i.id=m.executive_identity_id where m.workspace_id=target_workspace and m.status='Active' and m.archived_at is null and i.auth_user_id=auth.uid())$$;
create function public.has_workspace_permission(target_workspace uuid, requested text) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from workspace_memberships m join executive_identities i on i.id=m.executive_identity_id left join workspace_member_permissions mp on mp.membership_id=m.id left join workspace_permissions p on p.id=mp.permission_id where m.workspace_id=target_workspace and m.status='Active' and m.archived_at is null and i.auth_user_id=auth.uid() and (m.role='Owner' or (p.permission_key=requested and mp.effect='Allow')))$$;
revoke all on function public.is_active_workspace_member(uuid) from public;grant execute on function public.is_active_workspace_member(uuid) to authenticated;
revoke all on function public.has_workspace_permission(uuid,text) from public;grant execute on function public.has_workspace_permission(uuid,text) to authenticated;

create function public.create_business_table(table_name text, append_only boolean default false) returns void language plpgsql as $$begin execute format('create table public.%I(id uuid primary key, domain_id text not null, workspace_id uuid not null references public.workspaces(id), payload jsonb not null default ''{}'', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references public.executive_identities(id), version integer not null default 1 check(version>0), archived_at timestamptz, unique(workspace_id,domain_id))',table_name);if append_only then execute format('alter table public.%I add column sequence_number bigint not null check(sequence_number>=0), add column occurred_at timestamptz not null, add column recorded_at timestamptz not null default now(), add column correlation_id uuid not null, add column causation_id uuid',table_name);end if;end$$;
select public.create_business_table('executive_blueprints');
select public.create_business_table('executive_blueprint_revisions',true);
select public.create_business_table('blueprint_preferences');select public.create_business_table('blueprint_constraints');select public.create_business_table('blueprint_evidence');
select public.create_business_table('opportunities');select public.create_business_table('opportunity_provenance',true);select public.create_business_table('companies');select public.create_business_table('applications');select public.create_business_table('application_activities',true);select public.create_business_table('application_documents');
select public.create_business_table('career_ledger_entries',true);select public.create_business_table('compensation_records',true);select public.create_business_table('atlas_decision_snapshots',true);select public.create_business_table('knowledge_observations',true);select public.create_business_table('knowledge_signals');select public.create_business_table('discovery_runs',true);select public.create_business_table('document_versions',true);
select public.create_business_table('workspace_settings');select public.create_business_table('executive_settings');select public.create_business_table('entitlement_usage');
alter table public.opportunities add column company_id uuid references public.companies(id),add column title text,add column country text,add column industry text,add column status text,add column source_url text;
alter table public.companies add column name text,add column country text,add column industry text,add column ownership_type text;
alter table public.applications add column opportunity_id uuid references public.opportunities(id),add column company_id uuid references public.companies(id),add column stage text,add column submitted_at timestamptz,add column closed_at timestamptz,add constraint application_date_order check(closed_at is null or submitted_at is null or closed_at>=submitted_at);
alter table public.compensation_records add column opportunity_id uuid references public.opportunities(id),add column application_id uuid references public.applications(id),add column company_id uuid references public.companies(id),add column record_type text,add column currency text check(currency ~ '^[A-Z]{3}$'),add column amount_min numeric check(amount_min>=0),add column amount_max numeric check(amount_max>=0),add column amount_exact numeric check(amount_exact>=0),add column decision_date date,add constraint compensation_range_order check(amount_min is null or amount_max is null or amount_max>=amount_min);
alter table public.executive_blueprint_revisions add column blueprint_id uuid references public.executive_blueprints(id),add column revision_number integer not null check(revision_number>0),add constraint blueprint_revision_unique unique(workspace_id,blueprint_id,revision_number);
alter table public.opportunity_provenance add column opportunity_id uuid references public.opportunities(id),add column original_url text,add column original_id text,add column normalization_version text,add column import_run_id text,add column confidence numeric check(confidence between 0 and 100);
alter table public.career_ledger_entries add constraint ledger_workspace_sequence_unique unique(workspace_id,sequence_number);

create function public.reject_append_only_mutation() returns trigger language plpgsql as $$begin raise exception 'append-only table % does not permit %',tg_table_name,tg_op using errcode='55000';end$$;
do $$declare t text;begin foreach t in array array['career_ledger_entries','compensation_records','executive_blueprint_revisions','atlas_decision_snapshots','knowledge_observations','discovery_runs','document_versions'] loop execute format('create trigger %I before update or delete on public.%I for each row execute function public.reject_append_only_mutation()',t||'_append_only',t);end loop;end$$;

do $$declare t text;begin foreach t in array array['executive_identities','workspaces','workspace_memberships','workspace_invitations','workspace_permissions','workspace_member_permissions','executive_blueprints','executive_blueprint_revisions','blueprint_preferences','blueprint_constraints','blueprint_evidence','opportunities','opportunity_provenance','companies','applications','application_activities','application_documents','career_ledger_entries','compensation_records','atlas_decision_snapshots','knowledge_observations','knowledge_signals','discovery_runs','document_versions','workspace_settings','executive_settings','entitlement_usage'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;

create policy identities_self_read on public.executive_identities for select to authenticated using(auth_user_id=auth.uid());
create policy workspaces_member_read on public.workspaces for select to authenticated using(public.is_active_workspace_member(id));
create policy workspaces_owner_update on public.workspaces for update to authenticated using(owner_identity_id=(select id from public.executive_identities where auth_user_id=auth.uid())) with check(owner_identity_id=(select id from public.executive_identities where auth_user_id=auth.uid()));
create policy memberships_member_read on public.workspace_memberships for select to authenticated using(public.is_active_workspace_member(workspace_id));
create policy memberships_owner_write on public.workspace_memberships for all to authenticated using(public.has_workspace_permission(workspace_id,'Manage Workspace')) with check(public.has_workspace_permission(workspace_id,'Manage Workspace'));
create policy invitations_owner_manage on public.workspace_invitations for all to authenticated using(public.has_workspace_permission(workspace_id,'Invite Members')) with check(public.has_workspace_permission(workspace_id,'Invite Members'));
create policy permissions_authenticated_read on public.workspace_permissions for select to authenticated using(true);
create policy member_permissions_owner_manage on public.workspace_member_permissions for all to authenticated using(public.has_workspace_permission(workspace_id,'Manage Workspace')) with check(public.has_workspace_permission(workspace_id,'Manage Workspace'));

do $$declare t text;begin foreach t in array array['executive_blueprints','executive_blueprint_revisions','blueprint_preferences','blueprint_constraints','blueprint_evidence','opportunities','opportunity_provenance','companies','applications','application_activities','application_documents','career_ledger_entries','atlas_decision_snapshots','knowledge_observations','knowledge_signals','discovery_runs','document_versions','workspace_settings','executive_settings','entitlement_usage'] loop execute format('create policy %I on public.%I for select to authenticated using(public.is_active_workspace_member(workspace_id))',t||'_read',t);execute format('create policy %I on public.%I for insert to authenticated with check(public.is_active_workspace_member(workspace_id))',t||'_insert',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['executive_blueprints','blueprint_preferences','blueprint_constraints','blueprint_evidence','opportunities','opportunity_provenance','companies','applications','application_documents','knowledge_signals','workspace_settings','executive_settings','entitlement_usage'] loop execute format('create policy %I on public.%I for update to authenticated using(public.is_active_workspace_member(workspace_id)) with check(public.is_active_workspace_member(workspace_id))',t||'_update',t);end loop;end$$;
create policy compensation_read on public.compensation_records for select to authenticated using(public.has_workspace_permission(workspace_id,'View Compensation'));
create policy compensation_insert on public.compensation_records for insert to authenticated with check(public.has_workspace_permission(workspace_id,'View Compensation'));

drop function public.create_business_table(text,boolean);
commit;
