begin;

create table public.world_country_registry(
  code text primary key check(code ~ '^[A-Z]{2}$'),
  canonical_name text not null unique,
  region text,
  subregion text,
  aliases jsonb not null default '[]'::jsonb,
  supported_languages text[] not null default '{}',
  currency_code text check(currency_code is null or currency_code ~ '^[A-Z]{3}$'),
  provenance jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.world_country_registry enable row level security;
create policy world_country_registry_read on public.world_country_registry
  for select to authenticated using(true);

insert into public.world_country_registry(code,canonical_name,provenance) values
  ('AD','Andorra','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AE','United Arab Emirates','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AF','Afghanistan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AG','Antigua & Barbuda','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AI','Anguilla','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AL','Albania','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AM','Armenia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AO','Angola','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AQ','Antarctica','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AR','Argentina','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AS','Samoa (American)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AT','Austria','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AU','Australia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AW','Aruba','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AX','Åland Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('AZ','Azerbaijan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BA','Bosnia & Herzegovina','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BB','Barbados','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BD','Bangladesh','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BE','Belgium','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BF','Burkina Faso','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BG','Bulgaria','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BH','Bahrain','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BI','Burundi','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BJ','Benin','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BL','St Barthelemy','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BM','Bermuda','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BN','Brunei','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BO','Bolivia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BQ','Caribbean NL','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BR','Brazil','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BS','Bahamas','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BT','Bhutan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BV','Bouvet Island','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BW','Botswana','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BY','Belarus','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('BZ','Belize','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CA','Canada','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CC','Cocos (Keeling) Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CD','Congo (Dem. Rep.)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CF','Central African Rep.','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CG','Congo (Rep.)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CH','Switzerland','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CI','Côte d’Ivoire','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CK','Cook Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CL','Chile','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CM','Cameroon','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CN','China','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CO','Colombia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CR','Costa Rica','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CU','Cuba','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CV','Cape Verde','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CW','Curaçao','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CX','Christmas Island','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CY','Cyprus','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('CZ','Czech Republic','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('DE','Germany','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('DJ','Djibouti','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('DK','Denmark','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('DM','Dominica','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('DO','Dominican Republic','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('DZ','Algeria','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('EC','Ecuador','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('EE','Estonia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('EG','Egypt','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('EH','Western Sahara','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ER','Eritrea','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ES','Spain','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ET','Ethiopia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('FI','Finland','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('FJ','Fiji','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('FK','Falkland Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('FM','Micronesia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('FO','Faroe Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('FR','France','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GA','Gabon','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GB','Britain (UK)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GD','Grenada','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GE','Georgia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GF','French Guiana','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GG','Guernsey','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GH','Ghana','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GI','Gibraltar','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GL','Greenland','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GM','Gambia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GN','Guinea','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GP','Guadeloupe','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GQ','Equatorial Guinea','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GR','Greece','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GS','South Georgia & the South Sandwich Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GT','Guatemala','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GU','Guam','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GW','Guinea-Bissau','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('GY','Guyana','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('HK','Hong Kong','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('HM','Heard Island & McDonald Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('HN','Honduras','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('HR','Croatia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('HT','Haiti','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('HU','Hungary','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ID','Indonesia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IE','Ireland','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IL','Israel','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IM','Isle of Man','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IN','India','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IO','British Indian Ocean Territory','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IQ','Iraq','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IR','Iran','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IS','Iceland','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('IT','Italy','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('JE','Jersey','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('JM','Jamaica','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('JO','Jordan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('JP','Japan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KE','Kenya','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KG','Kyrgyzstan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KH','Cambodia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KI','Kiribati','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KM','Comoros','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KN','St Kitts & Nevis','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KP','Korea (North)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KR','Korea (South)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KW','Kuwait','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KY','Cayman Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('KZ','Kazakhstan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LA','Laos','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LB','Lebanon','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LC','St Lucia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LI','Liechtenstein','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LK','Sri Lanka','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LR','Liberia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LS','Lesotho','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LT','Lithuania','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LU','Luxembourg','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LV','Latvia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('LY','Libya','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MA','Morocco','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MC','Monaco','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MD','Moldova','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ME','Montenegro','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MF','St Martin (French)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MG','Madagascar','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MH','Marshall Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MK','North Macedonia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ML','Mali','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MM','Myanmar (Burma)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MN','Mongolia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MO','Macau','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MP','Northern Mariana Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MQ','Martinique','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MR','Mauritania','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MS','Montserrat','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MT','Malta','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MU','Mauritius','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MV','Maldives','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MW','Malawi','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MX','Mexico','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MY','Malaysia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('MZ','Mozambique','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NA','Namibia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NC','New Caledonia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NE','Niger','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NF','Norfolk Island','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NG','Nigeria','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NI','Nicaragua','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NL','Netherlands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NO','Norway','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NP','Nepal','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NR','Nauru','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NU','Niue','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('NZ','New Zealand','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('OM','Oman','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PA','Panama','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PE','Peru','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PF','French Polynesia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PG','Papua New Guinea','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PH','Philippines','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PK','Pakistan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PL','Poland','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PM','St Pierre & Miquelon','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PN','Pitcairn','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PR','Puerto Rico','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PS','Palestine','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PT','Portugal','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PW','Palau','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('PY','Paraguay','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('QA','Qatar','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('RE','Réunion','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('RO','Romania','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('RS','Serbia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('RU','Russia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('RW','Rwanda','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SA','Saudi Arabia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SB','Solomon Islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SC','Seychelles','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SD','Sudan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SE','Sweden','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SG','Singapore','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SH','St Helena','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SI','Slovenia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SJ','Svalbard & Jan Mayen','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SK','Slovakia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SL','Sierra Leone','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SM','San Marino','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SN','Senegal','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SO','Somalia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SR','Suriname','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SS','South Sudan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ST','Sao Tome & Principe','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SV','El Salvador','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SX','St Maarten (Dutch)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SY','Syria','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('SZ','Eswatini (Swaziland)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TC','Turks & Caicos Is','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TD','Chad','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TF','French S. Terr.','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TG','Togo','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TH','Thailand','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TJ','Tajikistan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TK','Tokelau','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TL','East Timor','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TM','Turkmenistan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TN','Tunisia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TO','Tonga','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TR','Turkey','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TT','Trinidad & Tobago','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TV','Tuvalu','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TW','Taiwan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('TZ','Tanzania','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('UA','Ukraine','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('UG','Uganda','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('UM','US minor outlying islands','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('US','United States','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('UY','Uruguay','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('UZ','Uzbekistan','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('VA','Vatican City','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('VC','St Vincent','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('VE','Venezuela','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('VG','Virgin Islands (UK)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('VI','Virgin Islands (US)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('VN','Vietnam','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('VU','Vanuatu','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('WF','Wallis & Futuna','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('WS','Samoa (western)','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('YE','Yemen','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('YT','Mayotte','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ZA','South Africa','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ZM','Zambia','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb),
  ('ZW','Zimbabwe','{"standard":"ISO 3166-1 alpha-2","evidenceStatus":"Verified","source":"IANA time-zone distribution ISO country table","sourceVersion":"2025-07-01"}'::jsonb)
on conflict(code) do update set canonical_name=excluded.canonical_name,provenance=excluded.provenance,updated_at=now();

comment on table public.world_country_registry is 'Canonical ISO 3166-1 country and territory identities. Null intelligence fields mean unavailable, never inferred.';

commit;

