import { DemoDataBanner } from "@/components/opportunities/demo-data-banner";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { SectionCard } from "@/components/section-card";
import { SourceCard } from "@/components/discovery/source-card";
import { RunHistoryTable } from "@/components/discovery/run-history-table";
import { StatusBadge } from "@/components/status-badge";
import { demoDiscoveryHealth, demoDiscoveryRuns, demoDiscoverySchedule, demoDiscoverySettings, demoDiscoveryStatistics, demoReliability } from "@/data/discovery-dashboard";
import { discoverySources } from "@/lib/discovery";
import { tierOneProviderPriorities } from "@/lib/discovery/provider-priorities";
import { productionProviderAdapters } from "@/lib/discovery/providers/production-catalog";

export default function DiscoveryPage() {
  const lastRun = demoDiscoveryRuns[0];
  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-6 lg:px-10">
    <PageHeader title="Opportunity Discovery" description="A source-agnostic control plane for finding, normalizing, and tracing executive opportunities." />
    <div className="mt-6"><DemoDataBanner /></div>
    <SectionCard className="mt-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="atlas-kicker">Coverage engine</p><h2 className="mt-3 text-xl font-semibold">One opportunity universe, continuously reconciled</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Approved providers enter a priority-aware collection queue, pass one validation and normalization pipeline, and reconcile into one canonical opportunity. Source attribution, freshness, lifecycle, quality, retries, and failures remain visible before Atlas evaluates the evidence.</p></div><StatusBadge tone="success">Engine ready</StatusBadge></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Schedule","Priority and refresh policy"],["Normalize","One Opportunity object"],["Reconcile","Cross-source duplicates"],["Observe","Health, freshness and quality"]].map(([title,detail])=><div key={title} className="rounded-xl border border-white/10 bg-slate-950/40 p-4"><p className="font-medium text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">{productionProviderAdapters.length} approved collection routes share one controlled adapter boundary. Employer-direct evidence remains authoritative over attributed job-board observations.</p></SectionCard>
    <section className="grid gap-4 py-6 sm:grid-cols-2 xl:grid-cols-4" aria-label="Discovery statistics">
      <MetricCard label="Available sources" value={discoverySources.length} />
      <MetricCard label="Mock opportunities" value={demoDiscoveryStatistics.opportunitiesFound} />
      <MetricCard label="Discovery confidence" value={`${demoDiscoveryStatistics.averageConfidence}%`} />
      <MetricCard label="Last discovery run" value={lastRun.id} />
    </section>

    <SectionCard><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Opportunity coverage</h2><p className="mt-2 text-sm text-slate-400">Eight employer-direct routes and two attributed public job feeds can now enter the common Opportunity Coverage Engine. Every observation follows the same normalization, canonical identity, freshness, monitoring, and quality controls.</p></div><StatusBadge tone="info">{productionProviderAdapters.length} production connectors</StatusBadge></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{discoverySources.map((source) => <SourceCard key={source.id} source={source} health={demoDiscoveryHealth.find((item) => item.source === source.id)} />)}</div></SectionCard>

    <SectionCard className="mt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="atlas-kicker">Founder-directed priorities</p><h2 className="mt-3 text-xl font-semibold">Tier 1 coverage</h2><p className="mt-2 max-w-3xl text-sm text-slate-400">Mandatory ecosystems remain visible even when contractual or legal authority is still required. Nothing is silently omitted or activated without a compliant access path.</p></div><StatusBadge tone="info">4 active · 2 gated</StatusBadge></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tierOneProviderPriorities.map((provider) => <article key={provider.id} className="rounded-xl border border-white/10 bg-slate-950/40 p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium text-white">{provider.name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{provider.strategy}</p></div><StatusBadge tone={provider.status === "implemented" ? "success" : "warning"}>{provider.status === "implemented" ? "Active" : "Approval gate"}</StatusBadge></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-600">Expected coverage</dt><dd className="mt-1 capitalize text-slate-300">{provider.expectedCoverage}</dd></div><div><dt className="text-slate-600">Operational risk</dt><dd className="mt-1 capitalize text-slate-300">{provider.operationalRisk}</dd></div></dl>{provider.fastestCompliantPath && <p className="mt-4 border-t border-white/10 pt-4 text-xs leading-5 text-amber-200/80">{provider.fastestCompliantPath}</p>}</article>)}</div></SectionCard>

    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <SectionCard><h2 className="text-xl font-semibold">Discovery Schedule</h2><div className="mt-4 space-y-3">{demoDiscoverySchedule.map((schedule) => <article key={schedule.id} className="flex items-center justify-between gap-4 rounded-xl border border-white/10 bg-slate-950/40 p-4"><div><p className="font-medium capitalize text-white">{schedule.source}</p><p className="mt-1 text-sm text-slate-500">{schedule.nextRunAt ? `Next preview: ${new Date(schedule.nextRunAt).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })}` : "Runs only when requested"}</p></div><StatusBadge tone={schedule.enabled ? "success" : "neutral"}>{schedule.frequency}</StatusBadge></article>)}</div></SectionCard>
      <SectionCard><h2 className="text-xl font-semibold">Source Reliability</h2><div className="mt-4 space-y-3">{demoReliability.map(({ source, reliability }) => <article key={source} className="rounded-xl border border-white/10 bg-slate-950/40 p-4"><div className="flex items-center justify-between gap-4"><p className="font-medium text-white">{source}</p><StatusBadge tone={reliability.score >= 75 ? "success" : "warning"}>{reliability.rating} · {reliability.score}%</StatusBadge></div><p className="mt-2 text-sm text-slate-500">{reliability.rationale}</p></article>)}</div></SectionCard>
    </div>

    <SectionCard className="mt-6"><h2 className="text-xl font-semibold">Discovery Run History</h2><p className="mt-2 text-sm text-slate-400">Demonstration records show the audit shape for future discovery activity.</p><div className="mt-4"><RunHistoryTable runs={demoDiscoveryRuns} /></div></SectionCard>

    <SectionCard className="mt-6"><h2 className="text-xl font-semibold">Discovery Settings</h2><p className="mt-2 text-sm text-slate-400">Per-source controls are previews only and cannot be changed in this sprint.</p><div className="mt-5 grid gap-4 lg:grid-cols-3">{demoDiscoverySettings.map((setting) => <article key={setting.source} className="rounded-xl border border-white/10 bg-slate-950/40 p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-medium capitalize text-white">{setting.source}</h3><StatusBadge tone={setting.enabled ? "success" : "neutral"}>{setting.enabled ? "Enabled" : "Disabled"}</StatusBadge></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Priority</dt><dd className="mt-1 text-slate-200">{setting.priority}</dd></div><div><dt className="text-slate-500">Maximum</dt><dd className="mt-1 text-slate-200">{setting.maximumResults}</dd></div><div><dt className="text-slate-500">Countries</dt><dd className="mt-1 text-slate-200">{setting.filters.countries.join(", ") || "Any"}</dd></div><div><dt className="text-slate-500">Languages</dt><dd className="mt-1 text-slate-200">{setting.filters.languages.join(", ") || "Any"}</dd></div></dl></article>)}</div></SectionCard>

    <p className="mt-6 text-xs text-slate-600">Coverage controls are workspace-isolated. Provider activation, automated scheduling, and production deployment remain explicit operational gates.</p>
  </div>;
}
